-- Diagnostic Stage 2 — Biology draft questions (biology_batch_01, 48 questions).
-- Generated by supabase/content/build.js from supabase/content/biology_batch_01.js.
--
-- These are DRAFTS: inserted as review_status 'draft' (validated false) and
-- never served until a person approves each one on the review page:
-- https://www.inspireacademic.org/teacher/question-review.html
-- Safe to re-run: a question already in the bank is skipped.
--
-- Needs supabase/diagnostic_questions_review.sql first.
-- Run in the LIVE project only:
-- https://supabase.com/dashboard/project/ygtsrdwoikqnrbexjrtl/sql/new

begin;

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Cell Biology$t$, $t$Magnification$t$, $t$aqa-bi-fh-cell-biology$t$, 3,
  $t$In a drawing, a cell is 50 mm long. The real cell is 0.1 mm long. What is the magnification?$t$,
  $t$\(\times 5\)$t$, $t$\(\times 0.002\)$t$, $t$\(\times 500\)$t$, $t$\(\times 50.1\)$t$, 'Not sure', $t$c$t$,
  $t$This multiplies the two sizes. Magnification = image size ÷ real size \(= 50 \div 0.1 = 500\).$t$, $t$This divides the real size by the image size. Use image ÷ real: \(50 \div 0.1 = 500\).$t$, null, $t$This adds the sizes. Magnification = image size ÷ real size \(= 500\).$t$,
  $t$Magnification = image size ÷ real size, both in the same units: \(50\,\text{mm} \div 0.1\,\text{mm} = \times 500\).$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$In a drawing, a cell is 50 mm long. The real cell is 0.1 mm long. What is the magnification?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Cell Biology$t$, $t$Units of Size$t$, $t$aqa-bi-fh-cell-biology$t$, 3,
  $t$A cell is 0.02 mm across. What is this in micrometres (\(\mu\text{m}\))?$t$,
  $t$\(2\,\mu\text{m}\)$t$, $t$\(20\,\mu\text{m}\)$t$, $t$\(200\,\mu\text{m}\)$t$, $t$\(0.00002\,\mu\text{m}\)$t$, 'Not sure', $t$b$t$,
  $t$This multiplies by 100. There are 1000 micrometres in a millimetre: \(0.02 \times 1000 = 20\,\mu\text{m}\).$t$, null, $t$This multiplies by 10 000. There are 1000 µm in 1 mm: \(0.02 \times 1000 = 20\,\mu\text{m}\).$t$, $t$This divides instead of multiplying. Micrometres are smaller units, so the number gets bigger: \(0.02 \times 1000 = 20\,\mu\text{m}\).$t$,
  $t$1 mm = 1000 µm, so \(0.02\,\text{mm} = 0.02 \times 1000 = 20\,\mu\text{m}\).$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$A cell is 0.02 mm across. What is this in micrometres (\(\mu\text{m}\))?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Cell Biology$t$, $t$Microscopy$t$, $t$aqa-bi-fh-cell-biology$t$, 2,
  $t$Why can an electron microscope show structures that a light microscope cannot?$t$,
  $t$It shows cells in natural colour$t$, $t$It can be used on living cells$t$, $t$It has a much higher resolution$t$, $t$It has a much lower magnification$t$, 'Not sure', $t$c$t$,
  $t$Electron micrographs are black and white (colour is added later). The key advantage is higher resolution.$t$, $t$Specimens for electron microscopes must be dead. The advantage is much higher resolution.$t$, null, $t$Electron microscopes have a much higher magnification as well as higher resolution.$t$,
  $t$Electron microscopes have much higher magnification and resolution, so they can distinguish structures that are very close together, such as ribosomes and the detail of mitochondria.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$Why can an electron microscope show structures that a light microscope cannot?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Cell Biology$t$, $t$Stem Cells$t$, $t$aqa-bi-fh-cell-biology$t$, 1,
  $t$What is a stem cell?$t$,
  $t$A cell found only in plant stems$t$, $t$A cell that has already specialised for a job$t$, $t$A cell that cannot divide to make new cells$t$, $t$An unspecialised cell that can differentiate$t$, 'Not sure', $t$d$t$,
  $t$Despite the name, stem cells are found in animals as well as plants.$t$, $t$It's the opposite: a stem cell is undifferentiated and can become other types of cell.$t$, $t$Stem cells can divide to make more cells, which can then differentiate.$t$, null,
  $t$A stem cell is an undifferentiated cell that can divide to make more cells and can differentiate into other types of cell.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$What is a stem cell?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Cell Biology$t$, $t$Meristems$t$, $t$aqa-bi-fh-cell-biology$t$, 2,
  $t$Where are stem cells found in plants?$t$,
  $t$In the palisade layer at the top of leaves$t$, $t$In meristems at root and shoot tips$t$, $t$In the xylem vessels$t$, $t$Only inside the seed coat$t$, 'Not sure', $t$b$t$,
  $t$Palisade cells are specialised for photosynthesis. Plant stem cells are in meristem tissue.$t$, null, $t$Xylem vessels are dead, specialised cells for carrying water. Stem cells are in the meristems.$t$, $t$Growing plants keep making new cells throughout life, from meristems at the tips of roots and shoots.$t$,
  $t$Meristem tissue at the tips of roots and shoots contains stem cells that can differentiate into any type of plant cell throughout the plant's life.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$Where are stem cells found in plants?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Cell Biology$t$, $t$Active Transport$t$, $t$aqa-bi-fh-cell-biology$t$, 3,
  $t$Root hair cells take in mineral ions from soil, where the ions are less concentrated than inside the cell. How?$t$,
  $t$By diffusion, down the concentration gradient$t$, $t$By osmosis, with the water$t$, $t$By active transport, using energy$t$, $t$By photosynthesis in the root$t$, 'Not sure', $t$c$t$,
  $t$Diffusion only moves particles from high to low concentration. Moving against the gradient needs active transport.$t$, $t$Osmosis moves water, not mineral ions. The ions move against their gradient by active transport.$t$, null, $t$Roots don't photosynthesise. The ions are taken up by active transport, using energy from respiration.$t$,
  $t$The ions move from a lower to a higher concentration, against the gradient, so the cells use active transport, which needs energy from respiration.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$Root hair cells take in mineral ions from soil, where the ions are less concentrated than inside the cell. How?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Cell Biology$t$, $t$Surface Area to Volume$t$, $t$aqa-bi-fh-cell-biology$t$, 3,
  $t$Why do large multicellular organisms need specialised exchange surfaces?$t$,
  $t$Their cells are bigger than in small ones$t$, $t$They need less oxygen for each cell$t$, $t$Their surface area to volume ratio is small$t$, $t$Their surface area to volume ratio is large$t$, 'Not sure', $t$c$t$,
  $t$Cell size isn't the issue. As an organism gets bigger, its surface area to volume ratio gets smaller.$t$, $t$Their cells still need oxygen, and many are far from the surface.$t$, null, $t$It's the other way round: larger organisms have a smaller surface area to volume ratio.$t$,
  $t$As an organism gets larger, its volume increases faster than its surface area, so its surface area to volume ratio falls. Diffusion across the body surface can't meet its needs, so it needs exchange surfaces (lungs, gills) and transport systems.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$Why do large multicellular organisms need specialised exchange surfaces?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Organisation$t$, $t$Enzyme Specificity$t$, $t$aqa-bi-fh-organisation$t$, 2,
  $t$Why does an enzyme work on only one type of substrate?$t$,
  $t$It is used up after catalysing one reaction$t$, $t$It is made of that same substrate$t$, $t$Other substrates denature it$t$, $t$Only that substrate fits its active site$t$, 'Not sure', $t$d$t$,
  $t$Enzymes are not used up; they catalyse reaction after reaction. They are specific because of the shape of the active site.$t$, $t$Enzymes are proteins. They are specific because only one substrate's shape fits the active site.$t$, $t$Denaturing is caused by high temperature or extreme pH, not by other substrates.$t$, null,
  $t$An enzyme's active site has a specific shape. Only a substrate with a complementary shape fits, like a key in a lock, so each enzyme catalyses one reaction.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$Why does an enzyme work on only one type of substrate?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Organisation$t$, $t$Digestive Enzymes$t$, $t$aqa-bi-fh-organisation$t$, 1,
  $t$Amylase breaks down starch. What does it produce?$t$,
  $t$Sugars$t$, $t$Amino acids$t$, $t$Fatty acids and glycerol$t$, $t$Proteins$t$, 'Not sure', $t$a$t$,
  null, $t$Amino acids come from proteins, broken down by protease. Amylase breaks starch into sugars.$t$, $t$Fatty acids and glycerol come from lipids, broken down by lipase.$t$, $t$Proteins are broken down by protease, not made by amylase.$t$,
  $t$Amylase is a carbohydrase: it breaks down starch into sugars (such as maltose).$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$Amylase breaks down starch. What does it produce?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Organisation$t$, $t$Gas Exchange in the Lungs$t$, $t$aqa-bi-fh-organisation$t$, 2,
  $t$How are the alveoli adapted for efficient gas exchange?$t$,
  $t$Thick walls to protect the blood$t$, $t$Few capillaries, so blood flows past slowly$t$, $t$A small area to trap the gases$t$, $t$Thin walls and a large surface area$t$, 'Not sure', $t$d$t$,
  $t$Thick walls would slow diffusion. Alveolar walls are one cell thick, giving a short diffusion path.$t$, $t$Alveoli have a rich blood supply, keeping concentration gradients steep.$t$, $t$A large surface area speeds up diffusion; millions of alveoli give a huge area.$t$, null,
  $t$Alveoli have a very large total surface area, walls one cell thick (a short diffusion path) and a rich blood supply that keeps concentration gradients steep.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$How are the alveoli adapted for efficient gas exchange?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Organisation$t$, $t$Coronary Heart Disease$t$, $t$aqa-bi-fh-organisation$t$, 2,
  $t$What does a stent do for a patient with coronary heart disease?$t$,
  $t$It replaces a faulty heart valve$t$, $t$It lowers the blood cholesterol$t$, $t$It keeps a narrowed artery open$t$, $t$It keeps the heartbeat regular$t$, 'Not sure', $t$c$t$,
  $t$Faulty valves are replaced with biological or mechanical valves. A stent holds a narrowed coronary artery open.$t$, $t$That is what statins do. A stent physically keeps a narrowed artery open.$t$, null, $t$That is a pacemaker's job. A stent keeps a coronary artery open.$t$,
  $t$In coronary heart disease, fatty material narrows the coronary arteries. A stent is a mesh tube inserted to keep the artery open, so blood can reach the heart muscle.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$What does a stent do for a patient with coronary heart disease?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Organisation$t$, $t$Transpiration$t$, $t$aqa-bi-fh-organisation$t$, 2,
  $t$Which change would increase the rate of transpiration?$t$,
  $t$A rise in temperature$t$, $t$A rise in humidity$t$, $t$Closing the stomata$t$, $t$Lower light intensity$t$, 'Not sure', $t$a$t$,
  null, $t$Humid air reduces the concentration gradient for water vapour, so transpiration slows.$t$, $t$Water vapour escapes through the stomata, so closing them reduces transpiration.$t$, $t$In dim light fewer stomata are open, so transpiration slows.$t$,
  $t$Transpiration increases with temperature (faster evaporation and diffusion), light intensity (more stomata open), air movement, and lower humidity.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$Which change would increase the rate of transpiration?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Organisation$t$, $t$Blood Components$t$, $t$aqa-bi-fh-organisation$t$, 1,
  $t$What is the job of platelets in the blood?$t$,
  $t$They carry oxygen$t$, $t$They help blood to clot$t$, $t$They engulf pathogens$t$, $t$They carry dissolved sugar$t$, 'Not sure', $t$b$t$,
  $t$Red blood cells carry oxygen. Platelets help the blood to clot.$t$, null, $t$White blood cells engulf pathogens. Platelets help the blood to clot.$t$, $t$Plasma carries dissolved substances such as glucose. Platelets help the blood to clot.$t$,
  $t$Platelets are fragments of cells that help the blood to clot at a wound, stopping bleeding and keeping pathogens out.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$What is the job of platelets in the blood?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Infection and Response$t$, $t$Measles$t$, $t$aqa-bi-fh-infection-response$t$, 1,
  $t$How is measles spread from person to person?$t$,
  $t$By drinking contaminated water$t$, $t$By insect bites$t$, $t$By droplets from coughs$t$, $t$By contaminated food$t$, 'Not sure', $t$c$t$,
  $t$Cholera and typhoid spread in contaminated water. Measles spreads by droplets from coughs and sneezes.$t$, $t$Malaria is spread by mosquito bites. Measles is spread in the air, by droplets.$t$, null, $t$Salmonella spreads in food. Measles is spread by inhaling droplets from coughs and sneezes.$t$,
  $t$Measles is a virus spread by inhaling droplets from an infected person's sneezes and coughs.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$How is measles spread from person to person?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Infection and Response$t$, $t$Salmonella$t$, $t$aqa-bi-fh-infection-response$t$, 2,
  $t$Which measures help control the spread of Salmonella food poisoning?$t$,
  $t$Spraying crops with fungicide$t$, $t$Sleeping under mosquito nets$t$, $t$Taking antibiotics for any cold or flu$t$, $t$Vaccinating poultry and cooking well$t$, 'Not sure', $t$d$t$,
  $t$Fungicides control fungal plant diseases. Salmonella is a bacterium spread in food.$t$, $t$Nets protect against malaria, which mosquitoes spread. Salmonella is spread in undercooked food.$t$, $t$Colds are caused by viruses, so antibiotics don't help, and this doesn't stop Salmonella.$t$, null,
  $t$Salmonella bacteria spread in food, especially undercooked poultry. In the UK, poultry are vaccinated against Salmonella, and cooking food thoroughly kills the bacteria.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$Which measures help control the spread of Salmonella food poisoning?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Infection and Response$t$, $t$Malaria$t$, $t$aqa-bi-fh-infection-response$t$, 1,
  $t$How is malaria spread?$t$,
  $t$By mosquitoes acting as vectors$t$, $t$By drinking contaminated water$t$, $t$By droplets in the air$t$, $t$By touching an infected person$t$, 'Not sure', $t$a$t$,
  null, $t$Malaria isn't waterborne. The protist is carried between people by mosquitoes.$t$, $t$Malaria isn't airborne. It is spread by mosquito bites.$t$, $t$Malaria isn't spread by touch. Mosquitoes carry it from person to person.$t$,
  $t$Malaria is caused by a protist. Mosquitoes act as vectors, carrying it between people when they feed on blood. Nets and insecticides that stop mosquito bites reduce its spread.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$How is malaria spread?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Infection and Response$t$, $t$White Blood Cells$t$, $t$aqa-bi-fh-infection-response$t$, 1,
  $t$Which is one way white blood cells defend the body?$t$,
  $t$They produce antibodies$t$, $t$They thicken the skin$t$, $t$They produce stomach acid$t$, $t$They carry oxygen to wounds$t$, 'Not sure', $t$a$t$,
  null, $t$The skin is a barrier in its own right; white blood cells don't thicken it. They produce antibodies.$t$, $t$Stomach acid is made by the stomach, not white blood cells.$t$, $t$Red blood cells carry oxygen. White blood cells fight pathogens, for example by producing antibodies.$t$,
  $t$White blood cells engulf pathogens (phagocytosis), produce antibodies against specific pathogens, and produce antitoxins.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$Which is one way white blood cells defend the body?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Infection and Response$t$, $t$Drug Trials$t$, $t$aqa-bi-fh-infection-response$t$, 2,
  $t$In a double-blind drug trial, who knows which patients receive the new drug?$t$,
  $t$Only the doctors$t$, $t$Only the patients$t$, $t$Both the doctors and the patients$t$, $t$Neither the doctors nor patients$t$, 'Not sure', $t$d$t$,
  $t$That would be a single-blind trial. In a double-blind trial the doctors don't know either.$t$, $t$Patients in a blind trial don't know. In a double-blind trial neither patients nor doctors know.$t$, $t$If both knew, the trial wouldn't be blind at all.$t$, null,
  $t$In a double-blind trial neither the patients nor the doctors know who receives the drug and who receives a placebo until the end, which removes bias from the results.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$In a double-blind drug trial, who knows which patients receive the new drug?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Infection and Response$t$, $t$Antibiotic Resistance$t$, $t$aqa-bi-fh-infection-response$t$, 3,
  $t$Why should a patient finish the whole course of antibiotics?$t$,
  $t$Because antibiotics also kill viruses$t$, $t$So all the bacteria are killed$t$, $t$So the body makes its own antibodies$t$, $t$Because they take a week to work$t$, 'Not sure', $t$b$t$,
  $t$Antibiotics don't kill viruses. The course is finished so that all the bacteria are killed, leaving no resistant survivors.$t$, null, $t$Antibiotics kill bacteria; they don't make the body produce antibodies (vaccines do that).$t$, $t$Antibiotics start working quickly. The course is finished so that no bacteria survive to become resistant.$t$,
  $t$Finishing the course kills all the bacteria, so none survive to mutate and form antibiotic-resistant strains that could spread.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$Why should a patient finish the whole course of antibiotics?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Infection and Response$t$, $t$Plant Disease$t$, $t$aqa-bi-fh-infection-response$t$, 3,
  $t$Tobacco mosaic virus (TMV) makes infected plants grow poorly. Why?$t$,
  $t$It destroys all the plant's roots$t$, $t$It makes the plant produce too much sugar$t$, $t$It blocks all the stomata so water can't escape$t$, $t$It discolours leaves, cutting photosynthesis$t$, 'Not sure', $t$d$t$,
  $t$TMV affects the leaves, not the roots. The mosaic pattern reduces photosynthesis.$t$, $t$The plant makes less sugar, not more, because the discoloured leaves photosynthesise less.$t$, $t$TMV doesn't block stomata. It discolours leaves, so less photosynthesis happens.$t$, null,
  $t$TMV causes a mosaic pattern of discoloured leaves. Less chlorophyll means less photosynthesis, so the plant makes less glucose and its growth is reduced.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', false, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$Tobacco mosaic virus (TMV) makes infected plants grow poorly. Why?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Bioenergetics$t$, $t$Photosynthesis is Endothermic$t$, $t$aqa-bi-fh-bioenergetics$t$, 1,
  $t$Photosynthesis is an endothermic reaction. What does this mean?$t$,
  $t$It gives out energy as heat$t$, $t$It only happens in the dark$t$, $t$It takes in energy from light$t$, $t$It needs no energy at all$t$, 'Not sure', $t$c$t$,
  $t$Giving out energy is exothermic. Photosynthesis takes in energy, transferred from the environment by light.$t$, $t$Photosynthesis needs light. Endothermic means it takes in energy.$t$, null, $t$Photosynthesis needs energy, which is transferred from light and absorbed by chlorophyll.$t$,
  $t$Endothermic reactions take in energy from the surroundings. In photosynthesis, energy is transferred to the chloroplasts by light.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$Photosynthesis is an endothermic reaction. What does this mean?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Bioenergetics$t$, $t$Uses of Glucose$t$, $t$aqa-bi-fh-bioenergetics$t$, 2,
  $t$Which is one way a plant uses the glucose it makes in photosynthesis?$t$,
  $t$To absorb light energy$t$, $t$To make mineral ions$t$, $t$To make cellulose for cell walls$t$, $t$To break down oxygen in respiration$t$, 'Not sure', $t$c$t$,
  $t$Chlorophyll absorbs light. Glucose is used for respiration, to make cellulose and starch, and more.$t$, $t$Mineral ions come from the soil; glucose can't be turned into them.$t$, null, $t$Oxygen isn't broken down. Glucose is used in respiration, and to make cellulose, starch, fats and proteins.$t$,
  $t$Plants use glucose for respiration, and to make cellulose (for cell walls), starch (for storage), fats and oils, and, with nitrate ions, amino acids for proteins.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$Which is one way a plant uses the glucose it makes in photosynthesis?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Bioenergetics$t$, $t$Light Intensity$t$, $t$aqa-bi-fh-bioenergetics$t$, 4,
  $t$A lamp is moved from 10 cm to 20 cm away from a plant. How does the light intensity reaching the plant change?$t$,
  $t$It halves$t$, $t$It doubles$t$, $t$It falls to a quarter$t$, $t$It falls to an eighth$t$, 'Not sure', $t$c$t$,
  $t$Light intensity doesn't fall in simple proportion. It follows the inverse square law: doubling the distance gives \(\tfrac{1}{2^{2}} = \tfrac{1}{4}\).$t$, $t$Moving the lamp further away lowers the intensity. By the inverse square law it falls to a quarter.$t$, null, $t$That would be an inverse cube. Light intensity \(\propto \tfrac{1}{d^{2}}\), so doubling the distance gives a quarter.$t$,
  $t$Light intensity is inversely proportional to the square of the distance: \(I \propto \tfrac{1}{d^{2}}\). Doubling the distance makes it \(\tfrac{1}{2^{2}} = \tfrac{1}{4}\) of what it was.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$A lamp is moved from 10 cm to 20 cm away from a plant. How does the light intensity reaching the plant change?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Bioenergetics$t$, $t$Oxygen Debt$t$, $t$aqa-bi-fh-bioenergetics$t$, 3,
  $t$Why do you keep breathing hard for a while after vigorous exercise stops?$t$,
  $t$To remove extra glucose from the blood$t$, $t$To repay the oxygen debt from lactic acid$t$, $t$Because the heart has slowed down$t$, $t$To cool the body down more quickly$t$, 'Not sure', $t$b$t$,
  $t$Extra breathing supplies oxygen; it doesn't remove glucose. The oxygen is needed to deal with the lactic acid.$t$, null, $t$The heart rate stays high too, to carry oxygen and lactic acid.$t$, $t$Sweating cools the body. Deep breathing supplies the oxygen needed to break down lactic acid.$t$,
  $t$During vigorous exercise, anaerobic respiration builds up lactic acid, creating an oxygen debt. Afterwards extra oxygen is needed to react with the lactic acid (in the liver it is converted back to glucose), so breathing stays deep and fast.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$Why do you keep breathing hard for a while after vigorous exercise stops?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Bioenergetics$t$, $t$Fermentation$t$, $t$aqa-bi-fh-bioenergetics$t$, 2,
  $t$What are the products of anaerobic respiration in yeast?$t$,
  $t$Lactic acid only$t$, $t$Carbon dioxide and water only$t$, $t$Ethanol and oxygen$t$, $t$Ethanol and carbon dioxide$t$, 'Not sure', $t$d$t$,
  $t$Lactic acid is made by anaerobic respiration in muscles. Yeast makes ethanol and carbon dioxide.$t$, $t$Carbon dioxide and water come from aerobic respiration.$t$, $t$Respiration uses oxygen rather than producing it. Yeast's anaerobic respiration makes ethanol and carbon dioxide.$t$, null,
  $t$In yeast, anaerobic respiration (fermentation): glucose → ethanol + carbon dioxide. This is used in making bread and alcoholic drinks.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$What are the products of anaerobic respiration in yeast?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Bioenergetics$t$, $t$Metabolism$t$, $t$aqa-bi-fh-bioenergetics$t$, 2,
  $t$What is metabolism?$t$,
  $t$Digesting food in the stomach and gut$t$, $t$All the reactions in a cell or body$t$, $t$How fast the heart beats$t$, $t$Moving substances into cells$t$, 'Not sure', $t$b$t$,
  $t$Digestion is only part of it. Metabolism is the sum of all the reactions in a cell or the body.$t$, null, $t$Heart rate isn't metabolism. Metabolism is the sum of all the chemical reactions in the body.$t$, $t$That is transport (diffusion, osmosis, active transport). Metabolism is all the chemical reactions.$t$,
  $t$Metabolism is the sum of all the reactions in a cell or the body, such as respiration and building molecules like proteins, starch and lipids.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$What is metabolism?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Homeostasis and Response$t$, $t$Homeostasis$t$, $t$aqa-bi-fh-homeostasis$t$, 1,
  $t$What is homeostasis?$t$,
  $t$Keeping internal conditions stable$t$, $t$Growing in response to a change$t$, $t$Keeping body temperature very high$t$, $t$Removing all body waste at once$t$, 'Not sure', $t$a$t$,
  null, $t$Homeostasis is about regulating internal conditions, not growth.$t$, $t$Homeostasis keeps temperature at an optimum (about 37 °C in humans), not as high as possible.$t$, $t$Removing waste is part of it, but homeostasis is regulating internal conditions for cells and enzymes.$t$,
  $t$Homeostasis is the regulation of internal conditions (such as blood glucose, body temperature and water levels) to keep them optimal for cells and enzymes, in response to internal and external changes.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$What is homeostasis?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Homeostasis and Response$t$, $t$Diabetes$t$, $t$aqa-bi-fh-homeostasis$t$, 2,
  $t$What causes Type 1 diabetes?$t$,
  $t$The body's cells stop responding to insulin$t$, $t$Eating too much sugar as a child$t$, $t$The pancreas makes too little insulin$t$, $t$The liver makes too much glucagon$t$, 'Not sure', $t$c$t$,
  $t$That describes Type 2 diabetes. Type 1 is when the pancreas produces too little insulin.$t$, $t$Type 1 diabetes isn't caused by diet. The pancreas fails to produce enough insulin.$t$, null, $t$Glucagon isn't the cause. In Type 1 diabetes the pancreas produces too little insulin.$t$,
  $t$In Type 1 diabetes the pancreas produces insufficient insulin, so blood glucose can rise uncontrollably; it is treated with insulin injections. In Type 2, body cells no longer respond to insulin.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$What causes Type 1 diabetes?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Homeostasis and Response$t$, $t$Adrenaline$t$, $t$aqa-bi-fh-homeostasis$t$, 2,
  $t$What does adrenaline do in the body?$t$,
  $t$Lowers blood glucose after meals$t$, $t$Controls the body's basal metabolic rate$t$, $t$Triggers the release of an egg$t$, $t$Raises heart rate for fight or flight$t$, 'Not sure', $t$d$t$,
  $t$That is insulin. Adrenaline raises heart rate and prepares the body for fight or flight.$t$, $t$That is thyroxine. Adrenaline prepares the body for fight or flight.$t$, $t$That is LH. Adrenaline raises heart rate, boosting oxygen and glucose delivery.$t$, null,
  $t$Adrenaline is produced by the adrenal glands in times of fear or stress. It increases heart rate and boosts the delivery of oxygen and glucose to the brain and muscles, preparing the body for fight or flight.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$What does adrenaline do in the body?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Homeostasis and Response$t$, $t$Negative Feedback$t$, $t$aqa-bi-fh-homeostasis$t$, 3,
  $t$Thyroxine levels are controlled by negative feedback. What does this mean?$t$,
  $t$A change sets off a response that reverses it$t$, $t$A change sets off a response that makes it bigger$t$, $t$The hormone stops being made permanently$t$, $t$Levels rise until the gland runs out$t$, 'Not sure', $t$a$t$,
  null, $t$A response that amplifies a change is positive feedback. Negative feedback reverses the change.$t$, $t$Production is adjusted up or down, not switched off for good.$t$, $t$Negative feedback keeps levels within limits; they don't keep rising.$t$,
  $t$In negative feedback, a change away from normal triggers a response that brings the level back. If thyroxine is too high, less TSH is released, so less thyroxine is made (and vice versa).$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$Thyroxine levels are controlled by negative feedback. What does this mean?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Homeostasis and Response$t$, $t$Contraception$t$, $t$aqa-bi-fh-homeostasis$t$, 3,
  $t$How does an oral contraceptive containing oestrogen help prevent pregnancy?$t$,
  $t$It kills sperm in the vagina$t$, $t$It blocks the cervix with a barrier$t$, $t$It inhibits FSH, so no eggs mature$t$, $t$It removes eggs from the ovaries$t$, 'Not sure', $t$c$t$,
  $t$Killing sperm is what spermicides do. Oestrogen in the pill inhibits FSH, so eggs don't mature.$t$, $t$That is a barrier method, such as a diaphragm. Oestrogen works hormonally, by inhibiting FSH.$t$, null, $t$Eggs aren't removed. Inhibiting FSH means eggs don't mature in the first place.$t$,
  $t$Oral contraceptives containing oestrogen inhibit the production of FSH, so no eggs mature and none are released.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$How does an oral contraceptive containing oestrogen help prevent pregnancy?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Homeostasis and Response$t$, $t$Synapses$t$, $t$aqa-bi-fh-homeostasis$t$, 2,
  $t$How does a nerve impulse pass across a synapse?$t$,
  $t$An electrical signal jumps the gap$t$, $t$Chemicals diffuse across the gap$t$, $t$The two neurones fuse together$t$, $t$Blood carries it across$t$, 'Not sure', $t$b$t$,
  $t$The electrical impulse can't cross the gap. It triggers chemicals that diffuse across.$t$, null, $t$The neurones don't join; a synapse is a gap between them.$t$, $t$Blood carries hormones, not nerve impulses across synapses.$t$,
  $t$When an impulse reaches the end of a neurone, a chemical is released that diffuses across the synapse and binds to the next neurone, starting a new electrical impulse.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$How does a nerve impulse pass across a synapse?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Homeostasis and Response$t$, $t$The Eye$t$, $t$aqa-bi-fh-homeostasis$t$, 2,
  $t$What does the iris do when you move into bright light?$t$,
  $t$Makes the pupil larger$t$, $t$Makes the pupil smaller$t$, $t$Changes the lens's shape$t$, $t$Detects colour on the retina$t$, 'Not sure', $t$b$t$,
  $t$A larger pupil lets in more light, which happens in dim light. In bright light the pupil gets smaller.$t$, null, $t$The ciliary muscles change the lens shape to focus. The iris controls pupil size.$t$, $t$Cone cells in the retina detect colour. The iris controls how much light enters.$t$,
  $t$In bright light the iris's circular muscles contract and radial muscles relax, making the pupil smaller so less light enters the eye and the retina isn't damaged.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', false, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$What does the iris do when you move into bright light?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Inheritance, Variation and Evolution$t$, $t$Gametes$t$, $t$aqa-bi-fh-inheritance$t$, 1,
  $t$How many chromosomes are in a human egg cell?$t$,
  $t$23$t$, $t$46$t$, $t$92$t$, $t$22$t$, 'Not sure', $t$a$t$,
  null, $t$46 is in body cells. Gametes have half that number, 23, so fertilisation restores 46.$t$, $t$92 is double a body cell's number. Gametes have 23.$t$, $t$That forgets the sex chromosome. Each gamete has 23 chromosomes (22 plus an X or Y).$t$,
  $t$Gametes are made by meiosis and contain one set of chromosomes: 23 in humans. When an egg and sperm fuse, the full 46 is restored.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$How many chromosomes are in a human egg cell?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Inheritance, Variation and Evolution$t$, $t$Meiosis$t$, $t$aqa-bi-fh-inheritance$t$, 2,
  $t$What does meiosis produce?$t$,
  $t$Two identical body cells$t$, $t$Four identical gametes$t$, $t$Four genetically different gametes$t$, $t$Two cells with twice the chromosomes$t$, 'Not sure', $t$c$t$,
  $t$Two identical body cells are made by mitosis.$t$, $t$Meiosis mixes up genetic material, so the four gametes are all different.$t$, null, $t$Meiosis halves the chromosome number, it doesn't double it.$t$,
  $t$Meiosis makes four gametes, each with a single set of chromosomes and each genetically different from the others.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$What does meiosis produce?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Inheritance, Variation and Evolution$t$, $t$Sex Determination$t$, $t$aqa-bi-fh-inheritance$t$, 1,
  $t$What is the probability that a baby will be a boy?$t$,
  $t$25%$t$, $t$50%$t$, $t$75%$t$, $t$100%$t$, 'Not sure', $t$b$t$,
  $t$A Punnett square of XX × XY gives two XX and two XY outcomes out of four, so 50%.$t$, null, $t$Three out of four isn't right: half of all sperm carry Y, so 50%.$t$, $t$Half of sperm carry an X chromosome, so a girl is just as likely.$t$,
  $t$Mother XX × father XY. Half of the sperm carry X and half carry Y, so there is a 50% chance of XY (a boy) and 50% of XX (a girl).$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$What is the probability that a baby will be a boy?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Inheritance, Variation and Evolution$t$, $t$Genetic Crosses$t$, $t$aqa-bi-fh-inheritance$t$, 3,
  $t$Tall (T) is dominant to short (t) in pea plants. Two heterozygous plants (Tt × Tt) are crossed. What proportion of the offspring are expected to be short?$t$,
  $t$1 in 2$t$, $t$3 in 4$t$, $t$1 in 4$t$, $t$None$t$, 'Not sure', $t$c$t$,
  $t$Half are heterozygous (Tt), but they are tall. Only tt plants are short: 1 in 4.$t$, $t$3 in 4 are tall (TT or Tt). Only 1 in 4 is tt, which is short.$t$, null, $t$Both parents carry t, so a quarter of offspring get t from each: tt, which is short.$t$,
  $t$Tt × Tt gives TT : Tt : tt in the ratio 1 : 2 : 1. Only tt shows the recessive short phenotype, so 1 in 4 (25%) are expected to be short.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$Tall (T) is dominant to short (t) in pea plants. Two heterozygous plants (Tt × Tt) are crossed. What proportion of the offspring are expected to be short?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Inheritance, Variation and Evolution$t$, $t$Genetic Engineering$t$, $t$aqa-bi-fh-inheritance$t$, 2,
  $t$What happens in genetic engineering?$t$,
  $t$Two animals with useful traits are bred together$t$, $t$A gene from one organism is put into another$t$, $t$A new organism grows from a single cell$t$, $t$Mutations are caused to make new genes$t$, 'Not sure', $t$b$t$,
  $t$That is selective breeding. Genetic engineering moves a gene from one organism into another.$t$, null, $t$That describes cloning. Genetic engineering transfers a gene between organisms.$t$, $t$Genetic engineering doesn't rely on random mutations; it transfers a specific gene into another organism.$t$,
  $t$Genetic engineering modifies an organism's genome by introducing a gene from another organism to give a desired characteristic, for example bacteria engineered to make human insulin.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$What happens in genetic engineering?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Inheritance, Variation and Evolution$t$, $t$Selective Breeding$t$, $t$aqa-bi-fh-inheritance$t$, 3,
  $t$What is a risk of selective breeding?$t$,
  $t$It makes a new species in one generation$t$, $t$It always causes genetic disease$t$, $t$It moves genes between species$t$, $t$Inbreeding, which reduces variation$t$, 'Not sure', $t$d$t$,
  $t$Selective breeding takes many generations and doesn't create new species that quickly.$t$, $t$It can make inherited disorders more likely, but doesn't always cause them.$t$, $t$Moving genes between species is genetic engineering, not selective breeding.$t$, null,
  $t$Selective breeding can lead to inbreeding, reducing the gene pool. Some breeds become prone to disease or inherited defects, and less able to cope with new diseases or changes.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$What is a risk of selective breeding?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Inheritance, Variation and Evolution$t$, $t$Fossils$t$, $t$aqa-bi-fh-inheritance$t$, 2,
  $t$Why is the fossil record incomplete?$t$,
  $t$Fossils only form in the sea$t$, $t$Every fossil has already been found$t$, $t$Many soft-bodied organisms didn't fossilise$t$, $t$Early life forms were all too large to fossilise$t$, 'Not sure', $t$c$t$,
  $t$Fossils form in many places, not only the sea. Many early organisms were soft-bodied and decayed before fossilising.$t$, $t$New fossils are still being found. The record is incomplete because many organisms never fossilised.$t$, null, $t$Early life forms were mostly small and soft-bodied, which is why few fossilised.$t$,
  $t$Many early life forms were soft-bodied and left few traces. Many fossils have also been destroyed by geological activity, and many are still undiscovered.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$Why is the fossil record incomplete?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Inheritance, Variation and Evolution$t$, $t$Classification$t$, $t$aqa-bi-fh-inheritance$t$, 1,
  $t$In the name Homo sapiens, what does "Homo" refer to?$t$,
  $t$The species$t$, $t$The genus$t$, $t$The kingdom$t$, $t$The family$t$, 'Not sure', $t$b$t$,
  $t$The species is the second part, "sapiens". The first part is the genus.$t$, null, $t$The kingdom is Animalia. In the binomial name, the first word is the genus.$t$, $t$The family (Hominidae) isn't part of the binomial name. The first word is the genus.$t$,
  $t$In the binomial system, the first part of the name is the genus (Homo) and the second is the species (sapiens).$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$In the name Homo sapiens, what does "Homo" refer to?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Ecology$t$, $t$Quadrat Sampling$t$, $t$aqa-bi-fh-ecology$t$, 3,
  $t$A student counts 12 daisies in 4 quadrats, each \(1\,\text{m}^{2}\). The field is \(500\,\text{m}^{2}\). Estimate the number of daisies in the field.$t$,
  $t$6000$t$, $t$125$t$, $t$48$t$, $t$1500$t$, 'Not sure', $t$d$t$,
  $t$This multiplies the total count by the field area. First find the mean per quadrat: \(12 \div 4 = 3\) per \(\text{m}^{2}\), then \(3 \times 500 = 1500\).$t$, $t$This divides the area by the number of quadrats. Use the mean per \(\text{m}^{2}\): \(3 \times 500 = 1500\).$t$, $t$This multiplies the count by the number of quadrats. Mean per \(\text{m}^{2}\) \(= 3\), so \(3 \times 500 = 1500\).$t$, null,
  $t$Mean per quadrat \(= 12 \div 4 = 3\) daisies per \(\text{m}^{2}\). Estimated population \(= 3 \times 500 = 1500\).$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$A student counts 12 daisies in 4 quadrats, each \(1\,\text{m}^{2}\). The field is \(500\,\text{m}^{2}\). Estimate the number of daisies in the field.$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Ecology$t$, $t$Transects$t$, $t$aqa-bi-fh-ecology$t$, 2,
  $t$What is a transect used for in fieldwork?$t$,
  $t$Counting organisms in one square metre$t$, $t$Showing how a species changes across an area$t$, $t$Measuring the temperature of a habitat$t$, $t$Catching and marking animals to estimate numbers$t$, 'Not sure', $t$b$t$,
  $t$A single quadrat samples one small area. A transect shows how distribution changes along a line.$t$, null, $t$Temperature is measured with a thermometer. A transect shows changes in distribution across a habitat.$t$, $t$Capture–recapture uses marking. A transect is a line along which you sample.$t$,
  $t$A transect is a line across a habitat, with quadrats placed along it, to show how the distribution of a species changes, for example from a hedge into a field.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$What is a transect used for in fieldwork?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Ecology$t$, $t$Decomposers$t$, $t$aqa-bi-fh-ecology$t$, 2,
  $t$What is the role of decomposers in the carbon cycle?$t$,
  $t$They take in carbon dioxide$t$, $t$They respire, releasing carbon dioxide$t$, $t$They turn dead matter into fossil fuels$t$, $t$They release only nitrogen gas$t$, 'Not sure', $t$b$t$,
  $t$Producers take in carbon dioxide (photosynthesis). Decomposers release it by respiring.$t$, null, $t$Fossil fuels form over millions of years when decay is prevented; decomposers break matter down instead.$t$, $t$Decomposers release carbon dioxide as they respire, returning carbon to the atmosphere.$t$,
  $t$Decomposers (bacteria and fungi) break down dead organisms and waste. As they respire they release carbon dioxide to the atmosphere, and mineral ions return to the soil.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$What is the role of decomposers in the carbon cycle?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Ecology$t$, $t$Deforestation$t$, $t$aqa-bi-fh-ecology$t$, 3,
  $t$Why does large-scale deforestation increase carbon dioxide in the atmosphere?$t$,
  $t$Trees give out CO₂ as they grow$t$, $t$Felled land absorbs less oxygen$t$, $t$Cutting trees makes methane$t$, $t$Less photosynthesis, and burning adds CO₂$t$, 'Not sure', $t$d$t$,
  $t$Growing trees take in more carbon dioxide than they give out. Removing them reduces photosynthesis.$t$, $t$Oxygen isn't the issue. Fewer trees photosynthesise, and burning or decaying wood releases carbon dioxide.$t$, $t$Methane comes mainly from cattle and rice fields. Deforestation adds carbon dioxide.$t$, null,
  $t$Fewer trees means less carbon dioxide is removed by photosynthesis, and burning or decaying the wood releases the carbon it stored as carbon dioxide.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$Why does large-scale deforestation increase carbon dioxide in the atmosphere?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Ecology$t$, $t$Interdependence$t$, $t$aqa-bi-fh-ecology$t$, 2,
  $t$In a food web, the only predator of rabbits dies out. What is likely to happen first?$t$,
  $t$The rabbit population rises$t$, $t$The rabbit population falls$t$, $t$The grass grows much more$t$, $t$Nothing changes in the web$t$, 'Not sure', $t$a$t$,
  null, $t$With no predator eating them, more rabbits survive, so their numbers rise at first.$t$, $t$More rabbits would eat more grass, so the grass is likely to decrease.$t$, $t$Species in a food web are interdependent, so removing one affects others.$t$,
  $t$With their predator gone, more rabbits survive to reproduce, so the rabbit population increases at first. That puts more pressure on the grass they eat.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$In a food web, the only predator of rabbits dies out. What is likely to happen first?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Ecology$t$, $t$Extremophiles$t$, $t$aqa-bi-fh-ecology$t$, 1,
  $t$What is an extremophile?$t$,
  $t$An organism that only eats animals$t$, $t$An organism that can't adapt to change$t$, $t$An organism found only in the cold$t$, $t$An organism living in extreme conditions$t$, 'Not sure', $t$d$t$,
  $t$That describes a carnivore. An extremophile lives in extreme conditions.$t$, $t$Extremophiles are highly adapted, to conditions such as high temperature, pressure or salt.$t$, $t$Extreme conditions include heat, high salt and high pressure, not just cold.$t$, null,
  $t$Extremophiles live in extreme environments, such as very high temperatures, high salt concentrations or high pressure, for example bacteria in deep-sea vents.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$What is an extremophile?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, combined_eligible, context_region)
select $t$Biology$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Ecology$t$, $t$Biomass Transfer$t$, $t$aqa-bi-fh-ecology$t$, 3,
  $t$Why is biomass lost at each stage of a food chain?$t$,
  $t$Each organism creates new energy$t$, $t$Predators eat all of their prey$t$, $t$Much is egested or used in respiration$t$, $t$Plants take biomass from the soil$t$, 'Not sure', $t$c$t$,
  $t$Energy can't be created. Biomass is lost because much isn't absorbed and much is used in respiration.$t$, $t$Predators don't eat every part of their prey, and much of what is eaten is lost.$t$, null, $t$Plants make biomass by photosynthesis, not from the soil. Biomass is lost between levels as waste and respiration.$t$,
  $t$Not all ingested material is absorbed (some is egested as faeces), and much of the absorbed material is used in respiration or lost as waste, so only a small fraction becomes biomass at the next level.$t$,
  $t$drafted-2026-09-27-biology-batch-01$t$, false, true, 'draft', 'mcq', false, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$Why is biomass lost at each stage of a food chain?$t$);

commit;

-- Check: the drafts from this batch.
select review_status, count(*) from public.diagnostic_questions
 where source = $t$drafted-2026-09-27-biology-batch-01$t$ group by 1;
