-- Diagnostic Stage 2 — Biology draft questions (biology_batch_04, 8 questions).
-- Generated by supabase/content/build.js from supabase/content/biology_batch_04.js
-- (batch drafted-2026-09-27-biology-batch-04-foundation-top-up). source is always 'ai_drafted': the live
-- diagnostic_questions_source_check constraint allows no other new value.
--
-- These are DRAFTS: inserted as review_status 'draft' (validated false) and
-- never served until a person approves each one on the review page:
-- https://www.inspireacademic.org/teacher/question-review.html
-- Safe to re-run: a question already in the bank is skipped.
--
-- Needs supabase/diagnostic_questions_review.sql first.
-- Run in the LIVE project only:
-- https://supabase.com/dashboard/project/ygtsrdwoikqnrbexjrtl/sql/new

begin;

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Biology$t$, $t$Universal$t$, 'GCSE', $t$Foundation$t$, $t$Cell Biology$t$, $t$Specialised Cells$t$, $t$aqa-bi-fh-cell-biology$t$, 2,
  $t$A sperm cell has a tail and contains many mitochondria. Why does it need so many mitochondria?$t$,
  $t$To store food for the egg$t$, $t$To carry the genetic information$t$, $t$To release energy for swimming$t$, $t$To make proteins for the tail$t$, 'Not sure', $t$c$t$,
  $t$The egg cell stores food (in its cytoplasm), not the sperm.$t$, $t$The genetic information is carried in the nucleus, not the mitochondria.$t$, null, $t$Proteins are made by ribosomes, not mitochondria.$t$,
  $t$Mitochondria are where respiration happens. They release the energy the tail needs to swim to the egg.$t$,
  'ai_drafted', false, true, 'draft', 'mcq', null, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$A sperm cell has a tail and contains many mitochondria. Why does it need so many mitochondria?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Biology$t$, $t$Universal$t$, 'GCSE', $t$Foundation$t$, $t$Cell Biology$t$, $t$Mitosis$t$, $t$aqa-bi-fh-cell-biology$t$, 2,
  $t$A cut on your finger heals as new skin cells are made. Which type of cell division makes these new cells?$t$,
  $t$Mitosis$t$, $t$Meiosis$t$, $t$Fertilisation$t$, $t$Differentiation$t$, 'Not sure', $t$a$t$,
  null, $t$Meiosis makes gametes (sex cells), not body cells for growth and repair.$t$, $t$Fertilisation joins two gametes together. It is not cell division.$t$, $t$Differentiation is a cell becoming specialised. It does not make new cells.$t$,
  $t$Mitosis makes two identical cells, so it is used for growth and repair.$t$,
  'ai_drafted', false, true, 'draft', 'mcq', null, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$A cut on your finger heals as new skin cells are made. Which type of cell division makes these new cells?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Biology$t$, $t$Universal$t$, 'GCSE', $t$Foundation$t$, $t$Organisation$t$, $t$Bile$t$, $t$aqa-bi-fh-organisation$t$, 3,
  $t$Which organ makes bile?$t$,
  $t$Stomach$t$, $t$Pancreas$t$, $t$Gall bladder$t$, $t$Liver$t$, 'Not sure', $t$d$t$,
  $t$The stomach makes acid and protease enzymes, not bile.$t$, $t$The pancreas makes digestive enzymes, not bile.$t$, $t$The gall bladder stores bile, but the liver makes it.$t$, null,
  $t$Bile is made in the liver, stored in the gall bladder and released into the small intestine.$t$,
  'ai_drafted', false, true, 'draft', 'mcq', null, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$Which organ makes bile?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Biology$t$, $t$Universal$t$, 'GCSE', $t$Both$t$, $t$Organisation$t$, $t$The Heart$t$, $t$aqa-bi-fh-organisation$t$, 3,
  $t$Why is the muscle wall of the left ventricle thicker than the wall of the right ventricle?$t$,
  $t$It pumps blood only to the lungs$t$, $t$It pumps blood all around the body$t$, $t$It collects blood returning from the body$t$, $t$It carries deoxygenated blood$t$, 'Not sure', $t$b$t$,
  $t$The right ventricle pumps blood to the lungs, a short distance, so its wall is thinner.$t$, null, $t$The atria collect blood returning to the heart. Ventricles pump it out.$t$, $t$The left side carries oxygenated blood. Wall thickness is about how hard it has to pump.$t$,
  $t$The left ventricle pumps blood at high pressure around the whole body, so it needs a thicker muscle wall.$t$,
  'ai_drafted', false, true, 'draft', 'mcq', null, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$Why is the muscle wall of the left ventricle thicker than the wall of the right ventricle?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Biology$t$, $t$Universal$t$, 'GCSE', $t$Foundation$t$, $t$Infection and Response$t$, $t$Spread of Disease$t$, $t$aqa-bi-fh-infection-response$t$, 2,
  $t$Some pathogens spread through dirty drinking water. Which is the best way to reduce this spread?$t$,
  $t$Sleeping under bed nets$t$, $t$Wearing a face mask$t$, $t$Taking antibiotics every day as a precaution$t$, $t$Treating water before drinking it$t$, 'Not sure', $t$d$t$,
  $t$Bed nets stop mosquitoes (a vector), not pathogens in water.$t$, $t$Face masks reduce spread through the air, not through water.$t$, $t$Antibiotics don't prevent infection, don't work on viruses, and daily use causes resistance.$t$, null,
  $t$Boiling, filtering or chlorinating water kills or removes the pathogens before anyone drinks them.$t$,
  'ai_drafted', false, true, 'draft', 'mcq', null, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$Some pathogens spread through dirty drinking water. Which is the best way to reduce this spread?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Biology$t$, $t$Universal$t$, 'GCSE', $t$Foundation$t$, $t$Bioenergetics$t$, $t$Products of Photosynthesis$t$, $t$aqa-bi-fh-bioenergetics$t$, 1,
  $t$Which gas do plants give out during photosynthesis in daylight?$t$,
  $t$Carbon dioxide$t$, $t$Nitrogen$t$, $t$Oxygen$t$, $t$Hydrogen$t$, 'Not sure', $t$c$t$,
  $t$Plants take in carbon dioxide for photosynthesis; they don't give it out.$t$, $t$Nitrogen is not made in photosynthesis.$t$, null, $t$Hydrogen is not given out. The oxygen comes from the water the plant uses.$t$,
  $t$Carbon dioxide + water → glucose + oxygen. The oxygen is released into the air.$t$,
  'ai_drafted', false, true, 'draft', 'mcq', null, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$Which gas do plants give out during photosynthesis in daylight?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Biology$t$, $t$Universal$t$, 'GCSE', $t$Foundation$t$, $t$Homeostasis and Response$t$, $t$Hormones$t$, $t$aqa-bi-fh-homeostasis$t$, 2,
  $t$How are hormones carried from a gland to their target organ?$t$,
  $t$In the blood$t$, $t$Along nerves$t$, $t$Through the muscles$t$, $t$In the air we breathe$t$, 'Not sure', $t$a$t$,
  null, $t$Nerves carry electrical impulses. That is the nervous system, not hormones.$t$, $t$Muscles are effectors that respond. They don't carry hormones.$t$, $t$Hormones are chemicals made inside the body, not carried in air.$t$,
  $t$Glands release hormones into the bloodstream, which carries them to the target organs.$t$,
  'ai_drafted', false, true, 'draft', 'mcq', null, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$How are hormones carried from a gland to their target organ?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Biology$t$, $t$Universal$t$, 'GCSE', $t$Both$t$, $t$Inheritance, Variation and Evolution$t$, $t$Genetic Terms$t$, $t$aqa-bi-fh-inheritance$t$, 3,
  $t$A person has the alleles Bb for eye colour. Which term describes this?$t$,
  $t$Homozygous$t$, $t$Heterozygous$t$, $t$Recessive$t$, $t$Homozygous recessive$t$, 'Not sure', $t$b$t$,
  $t$Homozygous means two of the same allele, such as BB or bb.$t$, null, $t$Recessive describes one allele (b), not the pair.$t$, $t$Homozygous recessive is bb: two recessive alleles.$t$,
  $t$Bb has two different alleles, so it is heterozygous.$t$,
  'ai_drafted', false, true, 'draft', 'mcq', null, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Biology$t$ and question_text = $t$A person has the alleles Bb for eye colour. Which term describes this?$t$);

commit;

-- Check: drafts per subject (this batch adds 8 Biology drafts).
select subject, review_status, count(*) from public.diagnostic_questions
 where review_status = 'draft' group by 1, 2 order by 1;
