-- Diagnostic Stage 2 — Chemistry draft questions (chemistry_batch_04, 8 questions).
-- Generated by supabase/content/build.js from supabase/content/chemistry_batch_04.js
-- (batch drafted-2026-09-27-chemistry-batch-04-foundation-top-up). source is always 'ai_drafted': the live
-- diagnostic_questions_source_check constraint allows no other new value.
--
-- These are DRAFTS: inserted as review_status 'draft' (validated false) and
-- never served until a person approves each one on the review page:
-- https://www.inspireacademic.org/teacher/question-review.html
-- Safe to re-run: a question already in the bank is skipped.
--
-- Needs supabase/diagnostic_questions_review.sql first.
-- Run in the LIVE project only:
-- https://supabase.com/dashboard/project/ygtsrdwoikqnrbexjrtl/sql/new

begin;

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Chemistry$t$, $t$Universal$t$, 'GCSE', $t$Foundation$t$, $t$Energy Changes$t$, $t$Exothermic Reactions$t$, $t$aqa-ch-fh-energy-changes$t$, 1,
  $t$A student adds magnesium ribbon to dilute hydrochloric acid. The test tube gets warm. What type of reaction is this?$t$,
  $t$Endothermic$t$, $t$Exothermic$t$, $t$Neutralisation$t$, $t$Reversible$t$, 'Not sure', $t$b$t$,
  $t$An endothermic reaction takes in energy, so the surroundings get colder, not warmer.$t$, null, $t$Neutralisation is an acid reacting with a base or alkali. Magnesium is a metal, not a base.$t$, $t$A temperature rise tells you nothing about whether a reaction can go backwards.$t$,
  $t$The reaction gives out energy to the surroundings, so the temperature rises. That is an exothermic reaction.$t$,
  'ai_drafted', false, true, 'draft', 'mcq', null, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Chemistry$t$ and question_text = $t$A student adds magnesium ribbon to dilute hydrochloric acid. The test tube gets warm. What type of reaction is this?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Chemistry$t$, $t$Universal$t$, 'GCSE', $t$Foundation$t$, $t$Organic Chemistry$t$, $t$Fractional Distillation$t$, $t$aqa-ch-fh-organic$t$, 2,
  $t$In a fractionating column, where are the fractions with the smallest molecules collected?$t$,
  $t$In the middle of the column$t$, $t$At the bottom, where it is hottest$t$, $t$They are not collected; they stay in the crude oil$t$, $t$At the top, where it is coolest$t$, 'Not sure', $t$d$t$,
  $t$The middle fractions, such as kerosene and diesel, have medium-sized molecules.$t$, $t$The bottom collects the largest molecules, with the highest boiling points (such as bitumen).$t$, $t$All the fractions are collected. Small molecules evaporate easily and rise up the column.$t$, null,
  $t$Small molecules have low boiling points, so they stay as gases and rise to the cool top of the column before condensing.$t$,
  'ai_drafted', false, true, 'draft', 'mcq', null, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Chemistry$t$ and question_text = $t$In a fractionating column, where are the fractions with the smallest molecules collected?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Chemistry$t$, $t$Universal$t$, 'GCSE', $t$Foundation$t$, $t$Quantitative Chemistry$t$, $t$Relative Formula Mass$t$, $t$aqa-ch-fh-quantitative$t$, 2,
  $t$What is the relative formula mass \(M_{\text{r}}\) of water, \(\text{H}_{2}\text{O}\)? (Relative atomic masses: H = 1, O = 16)$t$,
  $t$18$t$, $t$17$t$, $t$32$t$, $t$3$t$, 'Not sure', $t$a$t$,
  null, $t$This counts only one hydrogen atom. The formula has two: 2 × 1 + 16.$t$, $t$This doubles the oxygen. The small 2 belongs to hydrogen, not oxygen.$t$, $t$This counts the atoms (3) instead of adding their masses.$t$,
  $t$Add the relative atomic masses of every atom: \(2 \times 1 + 16 = 18\).$t$,
  'ai_drafted', false, true, 'draft', 'mcq', null, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Chemistry$t$ and question_text = $t$What is the relative formula mass \(M_{\text{r}}\) of water, \(\text{H}_{2}\text{O}\)? (Relative atomic masses: H = 1, O = 16)$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Chemistry$t$, $t$Universal$t$, 'GCSE', $t$Both$t$, $t$Quantitative Chemistry$t$, $t$Conservation of Mass$t$, $t$aqa-ch-fh-quantitative$t$, 3,
  $t$A student heats \(2.4\,\text{g}\) of magnesium in air. The white powder formed has a mass of \(4.0\,\text{g}\). Why has the mass increased?$t$,
  $t$Mass was created during the reaction$t$, $t$The heat energy taken in added to the mass$t$, $t$Oxygen from the air joined the magnesium$t$, $t$The powder has air trapped inside it$t$, 'Not sure', $t$c$t$,
  $t$Mass is never created or destroyed in a reaction (conservation of mass). The extra mass came from somewhere.$t$, $t$Heat is energy, not matter. It does not add mass.$t$, null, $t$Magnesium oxide is a solid compound. The extra mass is oxygen atoms bonded to the magnesium, not loose air.$t$,
  $t$Magnesium reacts with oxygen to make magnesium oxide. The extra \(4.0 - 2.4 = 1.6\,\text{g}\) is the oxygen that joined it.$t$,
  'ai_drafted', false, true, 'draft', 'mcq', null, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Chemistry$t$ and question_text = $t$A student heats \(2.4\,\text{g}\) of magnesium in air. The white powder formed has a mass of \(4.0\,\text{g}\). Why has the mass increased?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Chemistry$t$, $t$Universal$t$, 'GCSE', $t$Foundation$t$, $t$Chemical Analysis$t$, $t$Chromatography$t$, $t$aqa-ch-fh-analysis$t$, 3,
  $t$On a chromatogram, a spot moves \(3\,\text{cm}\) and the solvent front moves \(6\,\text{cm}\). What is the \(R_{\text{f}}\) value of the spot?$t$,
  $t$2.0$t$, $t$0.5$t$, $t$3.0$t$, $t$9.0$t$, 'Not sure', $t$b$t$,
  $t$This divides the solvent distance by the spot distance: the ratio is upside down. An Rf value is never more than 1.$t$, null, $t$This is just the distance the spot moved. Divide it by the distance the solvent moved.$t$, $t$This adds the two distances. Rf = spot distance ÷ solvent distance.$t$,
  $t$\(R_{\text{f}} = \dfrac{\text{distance moved by spot}}{\text{distance moved by solvent}} = \dfrac{3}{6} = 0.5\).$t$,
  'ai_drafted', false, true, 'draft', 'mcq', null, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Chemistry$t$ and question_text = $t$On a chromatogram, a spot moves \(3\,\text{cm}\) and the solvent front moves \(6\,\text{cm}\). What is the \(R_{\text{f}}\) value of the spot?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Chemistry$t$, $t$Universal$t$, 'GCSE', $t$Both$t$, $t$Chemical Changes$t$, $t$Electrolysis$t$, $t$aqa-ch-fh-chemical-changes$t$, 3,
  $t$Molten lead bromide is electrolysed. What forms at the negative electrode (cathode)?$t$,
  $t$Bromine$t$, $t$Hydrogen$t$, $t$Lead$t$, $t$Oxygen$t$, 'Not sure', $t$c$t$,
  $t$Bromide ions are negative, so they move to the positive electrode (anode). Bromine forms there.$t$, $t$Hydrogen comes from water in a solution. A molten compound has no water.$t$, null, $t$Lead bromide contains no oxygen, so no oxygen can form.$t$,
  $t$Lead ions are positive, so they move to the negative electrode, gain electrons and form lead metal.$t$,
  'ai_drafted', false, true, 'draft', 'mcq', null, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Chemistry$t$ and question_text = $t$Molten lead bromide is electrolysed. What forms at the negative electrode (cathode)?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Chemistry$t$, $t$Universal$t$, 'GCSE', $t$Foundation$t$, $t$Chemistry of the Atmosphere$t$, $t$Atmospheric Pollutants$t$, $t$aqa-ch-fh-atmosphere$t$, 2,
  $t$Diesel generators are widely used in Lagos when the mains power goes off. Incomplete combustion of diesel makes a toxic gas with no colour or smell. Which gas is it?$t$,
  $t$Carbon dioxide$t$, $t$Nitrogen$t$, $t$Water vapour$t$, $t$Carbon monoxide$t$, 'Not sure', $t$d$t$,
  $t$Carbon dioxide is made by complete combustion. It is a greenhouse gas, but not the toxic one described here.$t$, $t$Nitrogen is already most of the air. Engines make nitrogen oxides, which are not odourless.$t$, $t$Water vapour is made by combustion but is harmless.$t$, null,
  $t$With too little oxygen, carbon in the fuel forms carbon monoxide. It stops the blood carrying oxygen, and you cannot see or smell it.$t$,
  'ai_drafted', false, true, 'draft', 'mcq', null, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Chemistry$t$ and question_text = $t$Diesel generators are widely used in Lagos when the mains power goes off. Incomplete combustion of diesel makes a toxic gas with no colour or smell. Which gas is it?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Chemistry$t$, $t$Universal$t$, 'GCSE', $t$Both$t$, $t$Rates and Equilibrium$t$, $t$Factors Affecting Rate$t$, $t$aqa-ch-fh-rates-equilibrium$t$, 3,
  $t$Powdered calcium carbonate reacts faster with hydrochloric acid than the same mass of large lumps. Why?$t$,
  $t$The powder has a smaller surface area$t$, $t$The powder particles move faster$t$, $t$The powder lowers the activation energy$t$, $t$The powder has a larger surface area$t$, 'Not sure', $t$d$t$,
  $t$Breaking lumps into powder exposes more surface, so the surface area gets larger, not smaller.$t$, $t$Grinding does not make particles move faster. Raising the temperature does that.$t$, $t$Lowering the activation energy is what a catalyst does. Powdering does not change it.$t$, null,
  $t$More surface is exposed to the acid, so collisions happen more often and the reaction is faster.$t$,
  'ai_drafted', false, true, 'draft', 'mcq', null, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Chemistry$t$ and question_text = $t$Powdered calcium carbonate reacts faster with hydrochloric acid than the same mass of large lumps. Why?$t$);

commit;

-- Check: drafts per subject (this batch adds 8 Chemistry drafts).
select subject, review_status, count(*) from public.diagnostic_questions
 where review_status = 'draft' group by 1, 2 order by 1;
