-- ================================================================
-- diagnostic_questions_chemistry_biology_seed.sql
--
-- Adds Chemistry (36) and Biology (28) questions to diagnostic_questions,
-- closing the gap found while scoping a combined Physics/Chemistry/
-- Biology diagnostic: at the time this was written, diagnostic_questions
-- held 36 validated Physics questions and ZERO for Chemistry, Biology,
-- or Maths — meaning only Physics diagnostics actually worked end to end,
-- despite all four subjects being selectable in assessment-engine.html's
-- picker. This closes Chemistry and Biology specifically (Maths still
-- has none after this file).
--
-- Shape follows the existing Physics rows exactly: subject, exam_board
-- 'AQA', level 'GCSE', tier 'Higher', 4 topics/subtopics-per-question,
-- 4 questions per topic (assessment-engine.html's shuffleByTopic() caps
-- display at 4 per topic regardless of how many exist, so 4 per topic
-- is the natural minimum that guarantees every topic is actually used).
-- Chemistry uses 9 topics (36 questions) matching Physics's exact shape.
-- Biology uses AQA's real 7 top-level GCSE Biology topics (28 questions)
-- rather than inventing 2 extra topics purely to hit 36 — Biology's
-- curriculum genuinely groups into 7, not 9, and topic list here is
-- taken directly from assets/js/spec-map-aqa.js's Biology.AQA array,
-- not invented.
--
-- specification_ref is 'TO_BE_VERIFIED' throughout, NOT a fabricated
-- clause number, unlike the pre-existing Physics rows (which already
-- contain specific-looking refs like "AQA 5.7.1.1" this file's author
-- has not independently verified and did not want to imitate without
-- checking). This matches the standing discipline already established
-- elsewhere in this repo's Lesson Factory pilots
-- (docs/production/INSPIRE-LESSON-PRODUCTION-BLUEPRINT.md Gate 1: "Any
-- unverified official specification claim must remain TO_BE_VERIFIED").
--
-- Every question is original content, written directly against the
-- GCSE AQA Chemistry/Biology specifications' actual topic names (per
-- spec-map-aqa.js), not adapted from any real past paper or other
-- copyrighted source.
--
-- Run once in the Supabase SQL editor.
-- ================================================================

-- ═══════════════════════════════════════════════════════════
-- CHEMISTRY — 9 topics × 4 questions = 36
-- ═══════════════════════════════════════════════════════════

INSERT INTO diagnostic_questions (subject, exam_board, level, tier, topic, subtopic, specification_ref, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer, misconception_a, misconception_b, misconception_c, misconception_d, explanation, mark_scheme_point, source, validated, active) VALUES

-- Topic: Atomic Structure
('Chemistry','AQA','GCSE','Higher','Atomic Structure','Structure of the Atom','TO_BE_VERIFIED',1,
 'What is the overall charge of an atom?',
 'Positive','Negative','Neutral','It depends on the element','Not sure','c',
 'The positive charge of the protons is not fully cancelled — this ignores the equal number of electrons.',
 'The negative charge of the electrons is not fully cancelled — this ignores the equal number of protons.',
 'Correct — the number of protons (positive) always equals the number of electrons (negative) in a neutral atom, so the charges cancel.',
 'The charge of a neutral atom does not depend on which element it is — this is true for every element.',
 'An atom contains equal numbers of protons and electrons. Protons carry a +1 charge and electrons carry a -1 charge, so their charges cancel exactly, giving the whole atom no overall charge.',
 'Number of protons = number of electrons, so charges cancel [1]',
 'ai_drafted', true, true),

('Chemistry','AQA','GCSE','Higher','Atomic Structure','Electronic Structure','TO_BE_VERIFIED',2,
 'An atom of sodium has the electronic structure 2,8,1. Which shell is the outermost (highest energy) shell?',
 'The first shell, containing 2 electrons','The second shell, containing 8 electrons','The third shell, containing 1 electron','All three shells are equally outermost','Not sure','c',
 'The first shell (closest to the nucleus) is filled first and is the innermost, lowest-energy shell, not the outermost.',
 'The second shell is full at 8 electrons but is not the outermost shell here — there is a third shell present.',
 'Correct — electron shells fill from the nucleus outward; the third shell, holding the single outer electron, is the outermost occupied shell.',
 'Shells are not all equivalent — they are filled in order from the nucleus outward, and the outermost occupied one determines reactivity.',
 'Electron shells fill in order starting from the shell closest to the nucleus. For sodium (2,8,1), the first shell holds 2, the second holds 8, and the third (outermost) holds the single remaining electron — this outer electron is why sodium is so reactive.',
 'Third shell is outermost, holds 1 electron [1]',
 'ai_drafted', true, true),

('Chemistry','AQA','GCSE','Higher','Atomic Structure','Isotopes','TO_BE_VERIFIED',3,
 'Chlorine-35 and chlorine-37 are both isotopes of chlorine. What is the same about them, and what is different?',
 'Same number of protons; different number of neutrons','Same number of neutrons; different number of protons','Same number of electrons only; both protons and neutrons differ','Same mass number; different atomic number','Not sure','a',
 'Correct — isotopes of the same element always have the same number of protons (same atomic number) but different numbers of neutrons, which changes the mass number.',
 'It is the number of protons, not neutrons, that stays the same between isotopes of one element — this has it backwards.',
 'The number of protons must also match for both to be chlorine at all, since atomic number defines the element.',
 'Isotopes of the same element share the same atomic number (proton number); it is the mass number that differs between them, not the reverse.',
 'Isotopes are atoms of the same element (same number of protons, so same atomic number) with different numbers of neutrons (so different mass numbers). Chlorine-35 has 18 neutrons; chlorine-37 has 20.',
 'Same protons/atomic number, different neutrons/mass number [1]',
 'ai_drafted', true, true),

('Chemistry','AQA','GCSE','Higher','Atomic Structure','The Periodic Table','TO_BE_VERIFIED',2,
 'Elements in the same group of the periodic table have similar chemical properties. Why?',
 'They have the same number of protons','They have the same number of electron shells','They have the same number of electrons in their outer shell','They have the same relative atomic mass','Not sure','c',
 'Number of protons determines which element it is, not which group it belongs to alongside other elements.',
 'Number of electron shells increases going down a group — elements in a group have different numbers of shells, not the same.',
 'Correct — elements in the same group have the same number of outer-shell electrons, which is what mainly determines how an element reacts.',
 'Relative atomic mass increases going down a group and is not what determines chemical similarity between elements.',
 'The group number of a main-group element tells you how many electrons are in its outer shell. Since chemical reactivity is driven mainly by outer-shell electrons, elements in the same group react in similar ways — for example, all Group 1 elements have 1 outer electron and are all very reactive metals.',
 'Same number of outer-shell electrons drives similar reactivity [1]',
 'ai_drafted', true, true),

-- Topic: Bonding
('Chemistry','AQA','GCSE','Higher','Bonding','Ionic Bonding','TO_BE_VERIFIED',2,
 'When sodium reacts with chlorine to form sodium chloride, what happens to the electrons?',
 'A sodium atom gains an electron from a chlorine atom','A sodium atom loses an electron to a chlorine atom','Sodium and chlorine atoms share a pair of electrons','No electrons move; only protons are exchanged','Not sure','b',
 'This has the electron transfer backwards — sodium loses, it does not gain, an electron in this reaction.',
 'Correct — sodium (1 outer electron) transfers it to chlorine (7 outer electrons, needing 1 more), forming Na+ and Cl- ions held together by ionic bonding.',
 'Sharing electrons describes covalent bonding, not the ionic bonding that occurs between a metal and a non-metal like sodium and chlorine.',
 'Protons are never exchanged in a chemical reaction — only electrons move between atoms; the identity of each element (its proton number) stays fixed.',
 'Sodium has one electron in its outer shell and chlorine has seven. Sodium transfers its outer electron to chlorine, forming a positive sodium ion (Na+) and a negative chloride ion (Cl-). The oppositely charged ions are then held together by strong electrostatic forces of attraction — ionic bonding.',
 'Electron transferred from sodium to chlorine, forming ions [1]',
 'ai_drafted', true, true),

('Chemistry','AQA','GCSE','Higher','Bonding','Covalent Bonding','TO_BE_VERIFIED',2,
 'What is a covalent bond?',
 'The transfer of electrons from one atom to another','A shared pair of electrons between two atoms','The attraction between oppositely charged ions','A delocalised sea of electrons around metal ions','Not sure','b',
 'Electron transfer describes ionic bonding, which occurs between metals and non-metals, not covalent bonding.',
 'Correct — a covalent bond is a shared pair of electrons between two atoms, typically between two non-metals, and it holds the atoms together because both nuclei are attracted to the shared pair.',
 'Attraction between oppositely charged ions describes ionic bonding, not covalent bonding.',
 'A delocalised sea of electrons describes metallic bonding, not covalent bonding.',
 'A covalent bond forms when two atoms (usually both non-metals) each contribute one electron to a shared pair. Both positive nuclei are attracted to this shared, negatively charged pair, holding the atoms together.',
 'Covalent bond = shared pair of electrons [1]',
 'ai_drafted', true, true),

('Chemistry','AQA','GCSE','Higher','Bonding','Metallic Bonding','TO_BE_VERIFIED',3,
 'Metals are good conductors of electricity. What property of metallic bonding explains this?',
 'Metal atoms are arranged in a rigid lattice','Metal ions are held together by strong covalent bonds','Delocalised electrons are free to move throughout the structure','Metal atoms share electrons in fixed pairs','Not sure','c',
 'The rigid lattice arrangement itself explains hardness and structure, but is not what allows charge to flow.',
 'Metallic bonding is not covalent bonding — metals do not form fixed covalent bonds between ions.',
 'Correct — in metallic bonding, outer electrons become delocalised (free to move throughout the whole structure), and this flow of charge carriers is what allows metals to conduct electricity.',
 'Electrons in metallic bonding are delocalised, not held in fixed pairs between specific atoms — that description applies to covalent bonding, not metallic.',
 'In a metal, the outer electrons of each atom become delocalised — free to move throughout the whole giant structure rather than staying with one atom. These mobile electrons can carry electrical charge through the metal, which is why metals conduct electricity (and heat).',
 'Delocalised electrons free to move carry charge [1]',
 'ai_drafted', true, true),

('Chemistry','AQA','GCSE','Higher','Bonding','Giant Covalent Structures','TO_BE_VERIFIED',3,
 'Diamond and graphite are both giant covalent structures made only of carbon, but diamond does not conduct electricity while graphite does. Why?',
 'Diamond has stronger covalent bonds than graphite','Every carbon atom in diamond forms 4 covalent bonds, leaving no free electrons; graphite''s carbons form only 3 bonds each, leaving one delocalised electron per atom','Diamond is a metal and graphite is not','Graphite has ionic bonds between its layers','Not sure','b',
 'Bond strength is not the reason for the difference in conductivity — both are strong covalent structures; the electron arrangement is what differs.',
 'Correct — each carbon in diamond uses all 4 outer electrons in 4 covalent bonds, so there are no free electrons to carry charge. In graphite, each carbon forms only 3 bonds, leaving one delocalised electron per atom, free to move between the layers and conduct electricity.',
 'Neither diamond nor graphite is a metal — both are non-metal giant covalent structures made entirely of carbon.',
 'Graphite''s layers are held together by weak forces between layers, not ionic bonds — the bonding within each layer is covalent.',
 'Diamond: each carbon atom forms 4 covalent bonds to 4 other carbons, using all of its outer electrons — no delocalised electrons remain, so diamond does not conduct. Graphite: each carbon forms only 3 covalent bonds within its layer, leaving one outer electron per atom delocalised and free to move, which lets graphite conduct electricity.',
 'Diamond: 4 bonds, no free electrons. Graphite: 3 bonds, 1 delocalised electron per atom [1]',
 'ai_drafted', true, true),

-- Topic: Quantitative Chemistry
('Chemistry','AQA','GCSE','Higher','Quantitative Chemistry','Relative Formula Mass','TO_BE_VERIFIED',2,
 'What is the relative formula mass (Mr) of carbon dioxide, CO2? (Ar: C = 12, O = 16)',
 '28','32','44','16','Not sure','c',
 'This adds only one oxygen instead of two — CO2 contains two oxygen atoms, not one.',
 'This doubles the oxygen contribution incorrectly — check the calculation: 12 + (16 x 2) = 44, not 32.',
 'Correct — Mr = 12 (one carbon) + 16 + 16 (two oxygens) = 44.',
 'This is the mass of oxygen alone, ignoring the carbon atom entirely.',
 'To find relative formula mass, add up the relative atomic masses of every atom shown in the formula. CO2 has one carbon (Ar = 12) and two oxygens (Ar = 16 each): 12 + 16 + 16 = 44.',
 'Mr = 12 + 16 + 16 = 44 [1]',
 'ai_drafted', true, true),

('Chemistry','AQA','GCSE','Higher','Quantitative Chemistry','Moles','TO_BE_VERIFIED',3,
 'How many moles are in 22 g of carbon dioxide, CO2? (Mr of CO2 = 44)',
 '0.5 mol','2 mol','22 mol','44 mol','Not sure','a',
 'Correct — moles = mass ÷ Mr = 22 ÷ 44 = 0.5 mol.',
 'This inverts the calculation — moles = mass divided by Mr, not Mr divided by mass.',
 'This confuses moles with mass in grams — 22 is the given mass, not the number of moles.',
 'This uses the Mr value itself as the answer, rather than dividing the mass by it.',
 'Moles = mass (g) ÷ Mr. Here, mass = 22 g and Mr(CO2) = 44, so moles = 22 ÷ 44 = 0.5 mol.',
 'moles = mass / Mr = 22/44 = 0.5 [1]',
 'ai_drafted', true, true),

('Chemistry','AQA','GCSE','Higher','Quantitative Chemistry','Limiting Reagents','TO_BE_VERIFIED',4,
 'In a reaction, a student has enough of reactant A to make 0.3 mol of product, but only enough of reactant B to make 0.2 mol of product. What determines the actual amount of product formed?',
 'Reactant A, because there is more of it available','Reactant B, because it runs out first and limits the reaction','The average of the two amounts, 0.25 mol','Whichever reactant is added to the flask first','Not sure','b',
 'Having more of reactant A available does not matter — the reaction stops once the reactant that runs out first (the limiting reagent) is used up.',
 'Correct — the limiting reagent is whichever reactant would produce the smaller amount of product; here that is reactant B, so only 0.2 mol of product can form before B runs out.',
 'Product amount is set by the limiting reagent specifically, not an average of both reactants'' potential yields.',
 'The order reactants are added does not determine the limiting reagent — it is whichever reactant is present in the smaller (relatively) amount that runs out first.',
 'The limiting reagent is the reactant that is completely used up first, stopping the reaction. It is identified by comparing how much product each reactant could theoretically produce — whichever gives the smaller amount is the limiting reagent, and that smaller amount is the actual yield.',
 'Limiting reagent = reactant producing the smaller product amount = 0.2 mol [1]',
 'ai_drafted', true, true),

('Chemistry','AQA','GCSE','Higher','Quantitative Chemistry','Percentage Yield','TO_BE_VERIFIED',2,
 'A reaction has a theoretical yield of 20 g but the student actually obtains 15 g. What is the percentage yield?',
 '75%','25%','133%','5%','Not sure','a',
 'Correct — percentage yield = (actual yield ÷ theoretical yield) x 100 = (15 ÷ 20) x 100 = 75%.',
 'This is 100% minus the answer, not the percentage yield itself.',
 'This inverts the fraction (theoretical ÷ actual instead of actual ÷ theoretical), giving a value over 100% which is not possible for percentage yield.',
 'This is simply the difference between the two masses (20 - 15), not a percentage.',
 'Percentage yield = (actual yield ÷ theoretical yield) x 100. Here that is (15 ÷ 20) x 100 = 75%. Percentage yield can never exceed 100%, since you cannot obtain more product than the maximum theoretically possible.',
 'Percentage yield = (15/20) x 100 = 75% [1]',
 'ai_drafted', true, true),

-- Topic: Chemical Changes
('Chemistry','AQA','GCSE','Higher','Chemical Changes','Reactivity Series','TO_BE_VERIFIED',2,
 'A piece of zinc is placed in copper sulfate solution. What happens, and why?',
 'Nothing happens, because zinc and copper are both metals','Zinc displaces copper, because zinc is more reactive than copper','Copper displaces zinc, because copper is more reactive than zinc','The solution evaporates, releasing sulfur dioxide gas','Not sure','b',
 'A displacement reaction does occur here — zinc is more reactive than copper, so a reaction takes place.',
 'Correct — zinc is higher in the reactivity series than copper, so it displaces copper from copper sulfate solution, forming zinc sulfate and depositing copper metal.',
 'This has the reactivity series backwards — zinc, not copper, is the more reactive metal in this pair.',
 'This is not what happens in a displacement reaction between a metal and a metal salt solution — no gas is released in this reaction.',
 'In a displacement reaction, a more reactive metal will displace a less reactive metal from a solution of its salt. Zinc is more reactive than copper, so zinc atoms give up electrons to become Zn2+ ions in solution, while Cu2+ ions gain electrons and are deposited as solid copper metal: Zn + CuSO4 -> ZnSO4 + Cu.',
 'More reactive metal (zinc) displaces less reactive metal (copper) [1]',
 'ai_drafted', true, true),

('Chemistry','AQA','GCSE','Higher','Chemical Changes','Electrolysis','TO_BE_VERIFIED',3,
 'During the electrolysis of molten lead bromide, at which electrode is lead metal produced, and why?',
 'At the anode (positive electrode), because Pb2+ ions are attracted there','At the cathode (negative electrode), because Pb2+ ions are attracted there and gain electrons','At the anode, because bromide ions are attracted there','Lead is produced at both electrodes equally','Not sure','b',
 'Positive Pb2+ ions are attracted to the negative electrode (cathode), not the positive anode — opposite charges attract.',
 'Correct — Pb2+ ions are positively charged, so they are attracted to the negative cathode, where they gain electrons (are reduced) to form neutral lead atoms.',
 'Bromide ions (Br-) are the ones attracted to the anode, not lead ions — this mixes up which ion goes to which electrode.',
 'The two electrodes produce different products in electrolysis — lead forms only at the cathode, while bromine gas forms at the anode.',
 'In electrolysis of molten lead bromide, the positive lead ions (Pb2+) are attracted to the negative cathode, where they each gain 2 electrons to become neutral lead atoms (reduction). The negative bromide ions (Br-) are attracted to the positive anode, where they lose electrons to form bromine gas (oxidation).',
 'Pb2+ attracted to cathode, gains electrons, forms lead metal [1]',
 'ai_drafted', true, true),

('Chemistry','AQA','GCSE','Higher','Chemical Changes','Acids and Alkalis','TO_BE_VERIFIED',1,
 'A solution has a pH of 3. What does this tell you about the solution?',
 'It is strongly alkaline','It is neutral','It is acidic','It is a pure metal oxide','Not sure','c',
 'A pH of 3 is well below 7, so the solution is acidic, not alkaline — pH values above 7 indicate alkalinity.',
 'A neutral solution has a pH of exactly 7, not 3.',
 'Correct — any pH below 7 indicates an acidic solution; the lower the number, the more strongly acidic it is.',
 'pH describes how acidic or alkaline a solution is, not whether it is a metal oxide — this is a category error.',
 'The pH scale runs from 0 to 14. A pH of 7 is neutral, values below 7 are acidic (the lower the number, the more strongly acidic), and values above 7 are alkaline (the higher the number, the more strongly alkaline).',
 'pH < 7 indicates an acidic solution [1]',
 'ai_drafted', true, true),

('Chemistry','AQA','GCSE','Higher','Chemical Changes','Neutralisation','TO_BE_VERIFIED',2,
 'What are the products when hydrochloric acid reacts with sodium hydroxide?',
 'Sodium chloride and water','Sodium chloride and hydrogen gas','Sodium oxide and water','Sodium chloride, water, and carbon dioxide','Not sure','a',
 'Correct — this is a neutralisation reaction between an acid and an alkali, producing a salt (sodium chloride) and water: HCl + NaOH -> NaCl + H2O.',
 'Hydrogen gas is released when an acid reacts with a reactive metal, not when it reacts with an alkali such as sodium hydroxide.',
 'Sodium oxide is not formed in this reaction — the products of acid + alkali are a salt and water.',
 'Carbon dioxide is released only when an acid reacts with a carbonate, not with an alkali like sodium hydroxide.',
 'When an acid reacts with an alkali (a soluble base), the products are always a salt and water — this is neutralisation. Hydrochloric acid + sodium hydroxide produces the salt sodium chloride, plus water: HCl + NaOH -> NaCl + H2O.',
 'Acid + alkali -> salt + water [1]',
 'ai_drafted', true, true),

-- Topic: Energy Changes
('Chemistry','AQA','GCSE','Higher','Energy Changes','Exothermic and Endothermic','TO_BE_VERIFIED',1,
 'In an exothermic reaction, what happens to the temperature of the surroundings?',
 'It increases, because energy is transferred to the surroundings','It decreases, because energy is taken in from the surroundings','It stays exactly the same','It depends on the state of the reactants','Not sure','a',
 'Correct — an exothermic reaction releases energy to the surroundings, so the surroundings'' temperature rises.',
 'This describes an endothermic reaction, where energy is taken in from the surroundings, causing the temperature to fall — the opposite of exothermic.',
 'The surrounding temperature does change in an exothermic reaction — energy is being transferred out, which is detectable as a temperature rise.',
 'The energy change (exothermic or endothermic) is a property of the reaction itself, not something that varies simply with the physical state of the reactants.',
 'An exothermic reaction transfers energy to the surroundings (often as heat), so the temperature of the surroundings increases. Combustion and neutralisation reactions are common examples of exothermic reactions.',
 'Exothermic: energy released to surroundings, temperature rises [1]',
 'ai_drafted', true, true),

('Chemistry','AQA','GCSE','Higher','Energy Changes','Bond Energies','TO_BE_VERIFIED',3,
 'During a chemical reaction, is energy released or absorbed when new bonds are formed?',
 'Energy is absorbed when bonds form','Energy is released when bonds form','No energy change occurs when bonds form','It depends only on whether the reaction is exothermic overall','Not sure','b',
 'Bond formation releases energy, not absorbs it — breaking bonds is the step that requires energy input.',
 'Correct — forming new bonds releases energy, because the new bonds are more stable (lower energy) than the separated atoms. Breaking bonds, by contrast, requires an input of energy.',
 'A real energy change does occur every time bonds form — this energy released is what makes bond breaking/forming central to explaining exothermic and endothermic reactions.',
 'Bond formation always releases energy, regardless of the reaction''s overall exothermic or endothermic classification — it is the balance between energy absorbed (breaking bonds) and energy released (forming bonds) that determines the overall reaction type.',
 'Breaking bonds always requires an input of energy (endothermic step), while forming bonds always releases energy (exothermic step). Whether the overall reaction is exothermic or endothermic depends on which of these two energy changes is larger.',
 'Bond formation releases energy; bond breaking requires energy [1]',
 'ai_drafted', true, true),

('Chemistry','AQA','GCSE','Higher','Energy Changes','Reaction Profiles','TO_BE_VERIFIED',2,
 'On a reaction profile diagram for an exothermic reaction, how does the energy level of the products compare with the energy level of the reactants?',
 'Products have higher energy than reactants','Products have lower energy than reactants','Products and reactants have exactly the same energy','It cannot be determined from a reaction profile','Not sure','b',
 'This describes an endothermic reaction profile, where products end up at a higher energy level than the reactants — the opposite of exothermic.',
 'Correct — in an exothermic reaction, energy is released overall, so the products end up at a lower energy level than the reactants on the reaction profile.',
 'If reactants and products had equal energy, no energy would be transferred at all, and the reaction would be neither exothermic nor endothermic.',
 'A reaction profile is specifically designed to show the relative energy levels of reactants and products, and the difference between them (the overall energy change) can be read directly from it.',
 'A reaction profile plots energy against the progress of the reaction. For an exothermic reaction, the products sit at a lower energy level than the reactants, because the reaction released energy overall to the surroundings.',
 'Exothermic profile: products lower energy than reactants [1]',
 'ai_drafted', true, true),

('Chemistry','AQA','GCSE','Higher','Energy Changes','Activation Energy','TO_BE_VERIFIED',2,
 'What is meant by the "activation energy" of a reaction?',
 'The total energy released by the reaction','The minimum energy that colliding particles need for a reaction to occur','The energy needed to break all the bonds in the reactants','The energy of the products at the end of the reaction','Not sure','b',
 'Total energy released describes the overall energy change of the reaction, not the activation energy, which is about the energy barrier to starting the reaction.',
 'Correct — activation energy is the minimum energy that particles must have when they collide for a reaction to actually happen; without enough of it, a collision will not result in a reaction.',
 'Activation energy is not necessarily the energy needed to break every bond in the reactants — it is the minimum energy barrier for a successful collision to occur, shown as the "hump" on a reaction profile.',
 'The energy of the products at the end is a separate point on the reaction profile, not the activation energy itself.',
 'Activation energy is the minimum amount of energy that particles need to have when they collide for the collision to result in a reaction. On a reaction profile, it is shown as the height of the "hump" between reactants and products.',
 'Activation energy = minimum energy needed for a successful collision [1]',
 'ai_drafted', true, true),

-- Topic: Rates and Equilibrium
('Chemistry','AQA','GCSE','Higher','Rates and Equilibrium','Collision Theory','TO_BE_VERIFIED',2,
 'According to collision theory, what two conditions must be met for a chemical reaction to occur between two particles?',
 'The particles must be the same size and have the same charge','The particles must collide, and with enough energy (at least the activation energy)','The particles must be in the same physical state','The particles must both be catalysts','Not sure','b',
 'Particle size and charge are not the conditions collision theory describes — collision theory is about whether particles collide, and with how much energy.',
 'Correct — collision theory states that particles must collide, and they must collide with at least the activation energy, for a reaction to actually take place.',
 'Reactants do not need to be in the same physical state for a reaction to occur — many reactions happen between particles in different states, such as a solid reacting with a gas.',
 'A catalyst is a substance that speeds up a reaction without being used up — reacting particles are not catalysts themselves.',
 'Collision theory states that for particles to react, they must first collide with each other, and that collision must have at least enough energy (the activation energy) to break the bonds needed to start the reaction. A collision without enough energy will not lead to a reaction.',
 'Reaction requires: collision + sufficient energy (>= activation energy) [1]',
 'ai_drafted', true, true),

('Chemistry','AQA','GCSE','Higher','Rates and Equilibrium','Factors Affecting Rate','TO_BE_VERIFIED',2,
 'Increasing the temperature of a reaction increases its rate. Why?',
 'Particles become larger and collide more easily','Particles move faster, so they collide more often and with more energy','The activation energy of the reaction decreases','Particles become less concentrated','Not sure','b',
 'Increasing temperature does not change the size of particles — it changes how fast they move.',
 'Correct — at higher temperatures, particles have more kinetic energy, so they move faster. This means they collide more frequently, and a greater proportion of those collisions have at least the activation energy, so more collisions are successful.',
 'Activation energy is a fixed property of a particular reaction — it does not change with temperature. What changes is the proportion of particles with enough energy to overcome it.',
 'Temperature does not directly change concentration — heating a fixed amount of reactant in a fixed volume does not reduce how much of it is present.',
 'Raising the temperature gives particles more kinetic energy, so they move faster. Faster-moving particles collide more often, and more of those collisions have energy greater than or equal to the activation energy, so a greater proportion of collisions are successful — increasing the rate of reaction.',
 'Higher temperature -> faster particles -> more frequent, more energetic collisions [1]',
 'ai_drafted', true, true),

('Chemistry','AQA','GCSE','Higher','Rates and Equilibrium','Reversible Reactions','TO_BE_VERIFIED',3,
 'What is meant by a "reversible reaction"?',
 'A reaction that only happens once and cannot be repeated','A reaction where the products can react together to reform the original reactants','A reaction that requires a catalyst to occur at all','A reaction between two reversible metals','Not sure','b',
 'A reversible reaction can happen repeatedly in both directions — this option describes something being one-off, which is the opposite idea.',
 'Correct — in a reversible reaction, the products of the forward reaction can react with each other to reform the original reactants; the reaction can proceed in both directions.',
 'A reversible reaction does not require a catalyst to occur — reversibility is about the reaction being able to go both forwards and backwards, independent of whether a catalyst is used.',
 '"Reversible metals" is not a real chemistry term — reversibility describes the reaction itself, not a property of specific metals.',
 'In a reversible reaction, the products can react together to reform the original reactants, so the reaction can go in both the forward and backward directions, often shown with a double arrow symbol (⇌).',
 'Reversible reaction: products can reform the original reactants [1]',
 'ai_drafted', true, true),

('Chemistry','AQA','GCSE','Higher','Rates and Equilibrium','Le Chatelier''s Principle','TO_BE_VERIFIED',4,
 'A reversible reaction at equilibrium is exothermic in the forward direction. According to Le Chatelier''s principle, what happens to the position of equilibrium if the temperature is increased?',
 'It shifts towards the products, increasing yield of the forward reaction','It shifts towards the reactants, favouring the backward (endothermic) reaction','It does not move at all, since equilibrium is unaffected by temperature','It shifts completely to products, with no reactants remaining','Not sure','b',
 'This is the effect for an endothermic forward reaction, not an exothermic one — with an exothermic forward reaction, increasing temperature favours the reverse direction instead.',
 'Correct — Le Chatelier''s principle says the equilibrium shifts to oppose the change. Increasing temperature favours the endothermic direction (which absorbs the extra energy); since the forward reaction here is exothermic, the backward (endothermic) reaction is favoured, shifting equilibrium towards the reactants.',
 'Temperature is one of the factors that does shift the position of equilibrium in a reversible reaction — this option incorrectly claims equilibrium is unaffected by it.',
 'Equilibrium shifts to favour one direction more than the other, but the reaction remains reversible — it does not go to 100% completion in either direction.',
 'Le Chatelier''s principle states that if a system at equilibrium is subjected to a change, the position of equilibrium shifts to counteract that change. Increasing temperature favours whichever direction is endothermic (since it absorbs the added energy). Since the forward reaction is exothermic here, the reverse (endothermic) reaction is favoured, shifting equilibrium towards the reactants and reducing yield of product.',
 'Equilibrium shifts to favour the endothermic direction when temperature rises [1]',
 'ai_drafted', true, true),

-- Topic: Organic Chemistry
('Chemistry','AQA','GCSE','Higher','Organic Chemistry','Alkanes','TO_BE_VERIFIED',1,
 'Alkanes are described as "saturated" hydrocarbons. What does "saturated" mean in this context?',
 'They contain only single covalent bonds between carbon atoms','They contain at least one carbon-carbon double bond','They dissolve completely in water','They contain only carbon atoms, no hydrogen','Not sure','a',
 'Correct — "saturated" means the molecule contains only single covalent bonds between carbon atoms, so it holds the maximum possible number of hydrogen atoms.',
 'The presence of a carbon-carbon double bond describes an unsaturated hydrocarbon (an alkene), not a saturated one like an alkane.',
 'Being saturated in chemistry does not refer to solubility in water — this is a different, everyday meaning of the word "saturated."',
 'Alkanes are hydrocarbons, meaning they contain both carbon and hydrogen atoms — a compound with no hydrogen would not be a hydrocarbon at all.',
 'A saturated hydrocarbon contains only single covalent bonds between its carbon atoms, meaning each carbon holds as many hydrogen atoms as possible. Alkanes (such as methane, CH4, and ethane, C2H6) are all saturated hydrocarbons.',
 'Saturated = only single C-C bonds [1]',
 'ai_drafted', true, true),

('Chemistry','AQA','GCSE','Higher','Organic Chemistry','Cracking','TO_BE_VERIFIED',2,
 'Why are long-chain hydrocarbons from crude oil "cracked" into shorter ones?',
 'To make them heavier and more viscous for use as fuel oil','To produce shorter, more useful hydrocarbons, including alkenes for making polymers','To remove all the carbon atoms from the molecule','To convert them directly into crude oil again','Not sure','b',
 'Cracking makes hydrocarbons lighter and less viscous, not heavier — this is the opposite of what cracking achieves.',
 'Correct — cracking breaks long-chain, less useful hydrocarbons into shorter, more useful ones, including smaller alkanes for fuels and alkenes, which are needed as the starting material for making polymers.',
 'Cracking breaks carbon-carbon bonds to produce shorter hydrocarbon molecules — it does not remove carbon atoms from the compound entirely.',
 'Crude oil is the raw material cracking starts from — cracking produces new, more useful products from it, not a route back to crude oil itself.',
 'Cracking is a process that breaks down long-chain hydrocarbons (which are in less demand) into shorter, more useful ones by heating them, sometimes with a catalyst. This produces smaller alkanes, useful as fuels, and alkenes, which are essential as the starting material for making polymers.',
 'Cracking produces shorter, more useful hydrocarbons and alkenes [1]',
 'ai_drafted', true, true),

('Chemistry','AQA','GCSE','Higher','Organic Chemistry','Alkenes','TO_BE_VERIFIED',2,
 'How can you test whether a hydrocarbon is an alkene rather than an alkane, using bromine water?',
 'An alkene will turn bromine water from orange to colourless; an alkane will not','An alkane will turn bromine water from orange to colourless; an alkene will not','Both alkanes and alkenes turn bromine water colourless','Neither alkanes nor alkenes react with bromine water','Not sure','a',
 'Correct — alkenes contain a reactive carbon-carbon double bond, which reacts with bromine water, decolourising it from orange to colourless. Alkanes, being saturated, do not react and the bromine water stays orange.',
 'This has the test result backwards — it is the alkene (unsaturated) that decolourises bromine water, not the alkane (saturated).',
 'Only alkenes decolourise bromine water; alkanes, lacking a reactive double bond, do not react with it and it stays orange.',
 'Alkenes do react with bromine water because of their reactive carbon-carbon double bond — this is exactly what makes the bromine water test useful for distinguishing them from alkanes.',
 'The bromine water test distinguishes alkenes from alkanes: alkenes have a reactive carbon-carbon double bond that reacts with bromine water, turning it from orange to colourless. Alkanes have no such double bond (they are saturated), so bromine water stays orange when mixed with an alkane.',
 'Alkene decolourises bromine water (orange to colourless); alkane does not [1]',
 'ai_drafted', true, true),

('Chemistry','AQA','GCSE','Higher','Organic Chemistry','Polymers','TO_BE_VERIFIED',2,
 'Poly(ethene) is made by joining together many small ethene molecules. What is this process called, and what type of molecules are the small starting units?',
 'Combustion; the small units are called catalysts','Polymerisation; the small units are called monomers','Electrolysis; the small units are called isotopes','Neutralisation; the small units are called alkalis','Not sure','b',
 'Combustion is a burning reaction, not the process of joining small molecules into a long chain.',
 'Correct — this process is called polymerisation, and the small molecules that join together to form the long-chain polymer are called monomers. In this case, many ethene monomers join to form the polymer poly(ethene).',
 'Electrolysis uses electricity to break down a compound — it is unrelated to joining small organic molecules into long polymer chains.',
 'Neutralisation is the reaction between an acid and a base — this is a completely different type of reaction from polymer formation.',
 'Polymerisation is the process by which many small molecules called monomers join together (usually via addition reactions across double bonds) to form one very long molecule called a polymer. Poly(ethene) is formed from many ethene (CH2=CH2) monomers joining together.',
 'Polymerisation joins monomers into a polymer [1]',
 'ai_drafted', true, true),

-- Topic: Chemical Analysis
('Chemistry','AQA','GCSE','Higher','Chemical Analysis','Chromatography','TO_BE_VERIFIED',3,
 'In paper chromatography, a substance with a higher Rf value travels further up the paper than a substance with a lower Rf value. Why?',
 'It is more strongly attracted to the stationary phase (the paper)','It is more soluble in the mobile phase (the solvent) relative to the stationary phase','It has a larger relative formula mass','It is a purer sample than the other substance','Not sure','b',
 'Being more strongly attracted to the stationary phase would make a substance travel less far, not more — this is the opposite of what a high Rf value indicates.',
 'Correct — a substance that is more soluble in the solvent (mobile phase) relative to how strongly it sticks to the paper (stationary phase) spends more time moving with the solvent, so it travels further, giving a higher Rf value.',
 'Rf value is about how the substance distributes between the two phases (solvent and paper), not directly about its relative formula mass.',
 'Rf value tells you about a substance''s identity (by comparison to known values), not about how pure a sample is — chromatography can show purity by whether one spot or several spots appear, not by the Rf value of a single spot.',
 'In chromatography, each substance distributes between the mobile phase (solvent, moving up the paper) and the stationary phase (the paper itself). A substance that is more soluble in the solvent relative to how strongly it binds to the paper spends more time being carried along by the solvent, travelling further up the paper and giving a higher Rf value (Rf = distance moved by substance ÷ distance moved by solvent).',
 'Higher Rf = more soluble in mobile phase relative to stationary phase [1]',
 'ai_drafted', true, true),

('Chemistry','AQA','GCSE','Higher','Chemical Analysis','Flame Tests','TO_BE_VERIFIED',1,
 'A student performs a flame test on an unknown metal compound and observes a lilac flame. Which metal ion is likely present?',
 'Sodium (Na+)','Potassium (K+)','Calcium (Ca2+)','Copper (Cu2+)','Not sure','b',
 'Sodium ions produce a persistent orange/yellow flame in a flame test, not lilac.',
 'Correct — potassium ions (K+) characteristically produce a lilac flame in a flame test.',
 'Calcium ions produce a brick-red/orange flame in a flame test, not lilac.',
 'Copper ions produce a blue-green flame in a flame test, not lilac.',
 'Different metal ions produce characteristic flame colours when heated, which can be used to identify them: lithium is red, sodium is orange/yellow, potassium is lilac, calcium is brick-red/orange, and copper is blue-green.',
 'Lilac flame indicates potassium ions [1]',
 'ai_drafted', true, true),

('Chemistry','AQA','GCSE','Higher','Chemical Analysis','Tests for Gases','TO_BE_VERIFIED',1,
 'How do you test for the presence of carbon dioxide gas?',
 'Hold a lit splint to the gas — a squeaky pop confirms carbon dioxide','Bubble the gas through limewater — it turns cloudy/milky if carbon dioxide is present','Hold a glowing splint in the gas — it relights if carbon dioxide is present','Test the gas with damp litmus paper — it turns red if carbon dioxide is present','Not sure','b',
 'A "squeaky pop" with a lit splint is the test for hydrogen gas, not carbon dioxide.',
 'Correct — bubbling a gas through limewater and observing it turn cloudy (milky) is the standard test for carbon dioxide.',
 'A glowing splint relighting is the test for oxygen gas, not carbon dioxide.',
 'Damp litmus paper turning red (and bleaching white) is associated with testing for chlorine gas, not carbon dioxide.',
 'The standard test for carbon dioxide gas is to bubble it through limewater (a solution of calcium hydroxide). If carbon dioxide is present, the limewater turns cloudy/milky, because it reacts to form insoluble calcium carbonate.',
 'CO2 turns limewater cloudy [1]',
 'ai_drafted', true, true),

('Chemistry','AQA','GCSE','Higher','Chemical Analysis','Tests for Ions','TO_BE_VERIFIED',3,
 'A student adds a few drops of sodium hydroxide solution to a solution of an unknown metal ion, and a blue precipitate forms. Which metal ion is most likely present?',
 'Calcium (Ca2+)','Copper (Cu2+)','Sodium (Na+)','Iron(III) (Fe3+)','Not sure','b',
 'Calcium ions form a white precipitate with sodium hydroxide, not a blue one.',
 'Correct — copper(II) ions (Cu2+) form a characteristic blue precipitate of copper hydroxide when sodium hydroxide solution is added.',
 'Sodium compounds are soluble and sodium ions do not form a precipitate with sodium hydroxide at all — a flame test, not this precipitate test, is used to identify sodium.',
 'Iron(III) ions form an orange/brown precipitate with sodium hydroxide, not a blue one.',
 'Adding sodium hydroxide solution to a solution containing certain metal ions produces an insoluble metal hydroxide precipitate with a colour characteristic of that metal ion. Copper(II) ions specifically give a blue precipitate; iron(III) gives orange/brown; calcium and magnesium both give white precipitates (magnesium and calcium can then be told apart using other tests, since sodium hydroxide alone gives the same white result for both).',
 'Blue precipitate with NaOH indicates Cu2+ ions [1]',
 'ai_drafted', true, true),

-- Topic: Chemistry of the Atmosphere
('Chemistry','AQA','GCSE','Higher','Chemistry of the Atmosphere','Composition of the Atmosphere','TO_BE_VERIFIED',1,
 'What is the approximate percentage of nitrogen in the Earth''s current atmosphere?',
 'About 21%','About 78%','About 0.04%','About 50%','Not sure','b',
 'About 21% is approximately the percentage of oxygen in the atmosphere, not nitrogen.',
 'Correct — the Earth''s current atmosphere is approximately 78% nitrogen, making it the most abundant gas present.',
 'About 0.04% is approximately the percentage of carbon dioxide in the atmosphere, not nitrogen.',
 'Nitrogen makes up roughly four-fifths (78%) of the atmosphere, considerably more than half.',
 'The Earth''s atmosphere today is approximately 78% nitrogen, 21% oxygen, with the remaining roughly 1% made up of other gases including argon and small amounts of carbon dioxide (about 0.04%).',
 'Nitrogen makes up approximately 78% of the atmosphere [1]',
 'ai_drafted', true, true),

('Chemistry','AQA','GCSE','Higher','Chemistry of the Atmosphere','Greenhouse Gases','TO_BE_VERIFIED',2,
 'Which of the following is a greenhouse gas that contributes to the enhanced greenhouse effect?',
 'Nitrogen','Oxygen','Carbon dioxide','Argon','Not sure','c',
 'Nitrogen, despite being the most abundant atmospheric gas, is not a significant greenhouse gas.',
 'Oxygen is essential for respiration and combustion but is not classified as a significant greenhouse gas.',
 'Correct — carbon dioxide is a key greenhouse gas; it absorbs and re-radiates infrared radiation from the Earth''s surface, and rising levels from human activity are linked to the enhanced greenhouse effect.',
 'Argon is a chemically unreactive noble gas present in small amounts in the atmosphere, and is not a significant greenhouse gas.',
 'Greenhouse gases (including carbon dioxide, methane, and water vapour) absorb infrared radiation reflected from the Earth''s surface and re-radiate some of it back down, warming the atmosphere. Human activities such as burning fossil fuels have increased carbon dioxide levels, contributing to an enhanced greenhouse effect and climate change.',
 'CO2 is a significant greenhouse gas [1]',
 'ai_drafted', true, true),

('Chemistry','AQA','GCSE','Higher','Chemistry of the Atmosphere','Carbon Footprint','TO_BE_VERIFIED',2,
 'What is meant by the "carbon footprint" of a product or activity?',
 'The mass of carbon it physically contains','The total amount of carbon dioxide and other greenhouse gases released over its full life cycle','The number of carbon atoms in its chemical formula','The distance it travels during manufacture, measured in kilometres','Not sure','b',
 'A product''s physical carbon content is a different (and usually much smaller) figure from its carbon footprint, which is about emissions caused, not atoms contained.',
 'Correct — carbon footprint is the total amount of carbon dioxide and other greenhouse gases released over the full life cycle of a product or activity, including production, use, and disposal.',
 'The number of carbon atoms in a chemical formula describes the substance''s composition, not the emissions caused by producing or using it.',
 'Carbon footprint accounts for total greenhouse gas emissions across a product''s whole life cycle, not simply the distance it travels during manufacture (though transport can contribute to it).',
 'A carbon footprint is a measure of the total greenhouse gas emissions (usually expressed as an equivalent mass of carbon dioxide) caused directly and indirectly by an activity or over the life cycle of a product, from production through to disposal.',
 'Carbon footprint = total greenhouse gas emissions over a product''s/activity''s life cycle [1]',
 'ai_drafted', true, true),

('Chemistry','AQA','GCSE','Higher','Chemistry of the Atmosphere','Atmospheric Pollutants','TO_BE_VERIFIED',3,
 'Burning fossil fuels containing sulfur impurities releases sulfur dioxide, which contributes to acid rain. What other common atmospheric pollutant forms when fuels burn at high temperatures in engines, from nitrogen and oxygen in the air itself, rather than from an impurity in the fuel?',
 'Carbon monoxide','Particulates (soot)','Oxides of nitrogen','Unburned hydrocarbons','Not sure','c',
 'Carbon monoxide forms from incomplete combustion of the fuel''s carbon content, not from nitrogen and oxygen in the air reacting together.',
 'Particulates (soot) are unburned carbon particles from incomplete combustion of the fuel itself, not a product of nitrogen and oxygen in the air reacting.',
 'Correct — at the high temperatures inside an engine, nitrogen and oxygen from the air react together to form oxides of nitrogen, which contribute to acid rain and photochemical smog.',
 'Unburned hydrocarbons are fuel that has passed through the engine without combusting fully — they come from the fuel itself, not from nitrogen and oxygen in the air.',
 'At the high temperatures reached inside an engine, nitrogen and oxygen from the air (rather than from the fuel) react together to form oxides of nitrogen (NOx). These contribute to acid rain and can react in sunlight to form photochemical smog, causing respiratory problems.',
 'High engine temperatures cause N2 + O2 in air to react, forming oxides of nitrogen [1]',
 'ai_drafted', true, true);


-- ═══════════════════════════════════════════════════════════
-- BIOLOGY — 7 topics (matching spec-map-aqa.js's Biology.AQA
-- array exactly) × 4 questions = 28
-- ═══════════════════════════════════════════════════════════

INSERT INTO diagnostic_questions (subject, exam_board, level, tier, topic, subtopic, specification_ref, difficulty, question_text, option_a, option_b, option_c, option_d, option_e, correct_answer, misconception_a, misconception_b, misconception_c, misconception_d, explanation, mark_scheme_point, source, validated, active) VALUES

-- Topic: Cell Biology
('Biology','AQA','GCSE','Higher','Cell Biology','Eukaryotic and Prokaryotic Cells','TO_BE_VERIFIED',1,
 'Which of the following is true of a prokaryotic cell, such as a bacterium, but not of a eukaryotic cell?',
 'It has a cell membrane','It contains genetic material','It has no nucleus — its DNA lies free in the cytoplasm','It is always larger than a eukaryotic cell','Not sure','c',
 'Both prokaryotic and eukaryotic cells have a cell membrane — this is not a distinguishing feature between them.',
 'Both prokaryotic and eukaryotic cells contain genetic material — this is not a distinguishing feature between them.',
 'Correct — prokaryotic cells, such as bacteria, have no nucleus; their DNA is a single loop lying free in the cytoplasm, unlike eukaryotic cells, where DNA is enclosed in a nucleus.',
 'Prokaryotic cells are typically much smaller than eukaryotic cells, not larger — this has the size comparison backwards.',
 'The key distinguishing feature is the nucleus: eukaryotic cells (such as animal and plant cells) have their genetic material enclosed within a nucleus, while prokaryotic cells (such as bacteria) have no nucleus — their DNA is a single loop of DNA free in the cytoplasm, sometimes with additional small rings called plasmids.',
 'Prokaryotic cells have no nucleus; DNA is free in the cytoplasm [1]',
 'ai_drafted', true, true),

('Biology','AQA','GCSE','Higher','Cell Biology','Cell Specialisation','TO_BE_VERIFIED',2,
 'A sperm cell has a long tail (flagellum) and many mitochondria. How do these features relate to its function?',
 'The tail is for photosynthesis and mitochondria store genetic information','The tail allows swimming towards the egg, and the many mitochondria provide the energy needed for this movement','The tail and mitochondria have no connection to the sperm cell''s function','The tail is used to absorb nutrients, and mitochondria control cell division','Not sure','b',
 'Sperm cells do not photosynthesise, and mitochondria are the site of respiration, not storage of genetic information.',
 'Correct — the tail allows the sperm cell to swim towards the egg cell, and the large number of mitochondria provide the energy (via aerobic respiration) needed to power this swimming movement.',
 'These features are specific adaptations that directly support the sperm cell''s function of reaching and fertilising an egg — they are not unrelated to what the cell does.',
 'The tail is for movement (swimming), not nutrient absorption, and mitochondria are the site of respiration for energy release, not control of cell division.',
 'A sperm cell is specialised for its function of fertilising an egg cell. Its long tail (flagellum) allows it to swim through fluid to reach the egg, and it contains a large number of mitochondria, which carry out aerobic respiration to release the energy needed to power this swimming movement.',
 'Tail enables swimming; many mitochondria provide energy for movement [1]',
 'ai_drafted', true, true),

('Biology','AQA','GCSE','Higher','Cell Biology','Diffusion, Osmosis and Active Transport','TO_BE_VERIFIED',3,
 'A plant cell is placed in a solution with a lower water concentration than the cell itself (i.e., a more concentrated solution). What is likely to happen to the cell, and by what process?',
 'Water moves into the cell by osmosis, and the cell swells','Water moves out of the cell by osmosis, and the cell becomes flaccid/plasmolysed','Water moves out of the cell by active transport, using energy','Glucose moves into the cell by diffusion','Not sure','b',
 'Water moves out of, not into, a cell placed in a more concentrated external solution — this describes the opposite direction of net water movement.',
 'Correct — water moves by osmosis from a region of higher water concentration (inside the cell) to a region of lower water concentration (the surrounding solution). This causes the cell to lose water, becoming flaccid, and in extreme cases the cell membrane pulls away from the cell wall (plasmolysis).',
 'Osmosis is the movement of water across a partially permeable membrane down a concentration gradient — it does not require energy input, unlike active transport.',
 'The question concerns the movement of water, driven by a concentration difference, which is osmosis — not the diffusion of a dissolved substance like glucose.',
 'Osmosis is the movement of water molecules from a region of higher water concentration to a region of lower water concentration, through a partially permeable membrane, without requiring energy. If the solution surrounding a plant cell has a lower water concentration than the cell''s contents, water moves out of the cell by osmosis, causing the cell to become flaccid and, if enough water is lost, plasmolysed.',
 'Water moves out of cell by osmosis; cell becomes flaccid/plasmolysed [1]',
 'ai_drafted', true, true),

('Biology','AQA','GCSE','Higher','Cell Biology','Mitosis','TO_BE_VERIFIED',2,
 'What is the purpose of mitosis in a multicellular organism?',
 'To produce four genetically different daughter cells for sexual reproduction','To produce two genetically identical daughter cells, for growth and repair of tissues','To halve the number of chromosomes for the production of gametes','To combine genetic material from two parent cells','Not sure','b',
 'Four genetically different daughter cells are produced by meiosis, for sexual reproduction — this describes meiosis, not mitosis.',
 'Correct — mitosis produces two genetically identical daughter cells from one parent cell, and is used by the body for growth and to replace damaged or worn-out cells.',
 'Halving the chromosome number for gamete production describes meiosis, not mitosis — mitosis keeps the chromosome number the same in daughter cells.',
 'Combining genetic material from two parent cells happens during fertilisation, not during mitosis, which involves only one parent cell dividing.',
 'Mitosis is a type of cell division that produces two new cells, each genetically identical to the parent cell and to each other, with the same number of chromosomes. It is used for growth of the organism, and to replace cells that are damaged or have worn out.',
 'Mitosis produces two genetically identical cells, for growth and repair [1]',
 'ai_drafted', true, true),

-- Topic: Organisation
('Biology','AQA','GCSE','Higher','Organisation','Enzymes','TO_BE_VERIFIED',2,
 'Why does an enzyme stop working (denature) if the temperature becomes too high?',
 'The enzyme freezes solid and can no longer move','The active site changes shape, so the substrate can no longer bind to it','The enzyme turns into a different type of molecule entirely','High temperature destroys the substrate but not the enzyme','Not sure','b',
 'Enzymes are proteins and do not freeze at high temperatures — the problem at high temperature is the opposite: too much energy disrupts the enzyme''s structure.',
 'Correct — at high temperatures, the bonds holding the enzyme''s 3D structure together break, changing the shape of its active site. Once the active site no longer fits the substrate, the enzyme can no longer catalyse the reaction, and is said to be denatured.',
 'Denaturing changes the shape of the enzyme''s protein structure, but it is still fundamentally a protein — it does not become an entirely different type of molecule.',
 'It is specifically the enzyme''s own structure — particularly its active site — that is affected by high temperature; this is what stops the reaction, not damage limited to the substrate alone.',
 'Enzymes are proteins with a specific 3D shape, including an active site that fits a particular substrate. At high temperatures, the bonds maintaining this 3D structure break, permanently changing the shape of the active site. Once the substrate no longer fits, the enzyme can no longer catalyse the reaction — this is called denaturing.',
 'High temperature changes active site shape, denaturing the enzyme [1]',
 'ai_drafted', true, true),

('Biology','AQA','GCSE','Higher','Organisation','The Digestive System','TO_BE_VERIFIED',1,
 'Which organ produces bile, which helps digest fats?',
 'The stomach','The liver','The pancreas','The small intestine','Not sure','b',
 'The stomach produces acid and protein-digesting enzymes, but it does not produce bile.',
 'Correct — bile is produced by the liver, then stored in the gallbladder before being released into the small intestine, where it helps digest fats by breaking large fat droplets into smaller ones (emulsification).',
 'The pancreas produces several digestive enzymes and releases them into the small intestine, but it does not produce bile — that is the liver''s role.',
 'The small intestine is where bile acts and where most digestion and absorption occurs, but bile itself is produced in the liver, not the small intestine.',
 'Bile is produced by the liver and stored in the gallbladder. It is released into the small intestine, where it neutralises stomach acid and emulsifies fats — breaking large fat droplets into smaller ones, which increases the surface area for lipase enzymes to digest the fat more efficiently.',
 'Bile is produced by the liver [1]',
 'ai_drafted', true, true),

('Biology','AQA','GCSE','Higher','Organisation','The Heart and Blood Vessels','TO_BE_VERIFIED',3,
 'Why do arteries have thick, muscular walls, while veins have thinner walls but contain valves?',
 'Arteries carry blood at high pressure away from the heart; veins carry blood at lower pressure back to the heart and need valves to prevent backflow','Arteries carry blood back to the heart, so need to be strong; veins carry blood away from the heart at low pressure','Both carry blood at the same pressure, so the wall differences are not functionally important','Veins need thick walls because they carry more blood overall than arteries','Not sure','a',
 'Correct — arteries carry blood away from the heart at high pressure, so need thick, muscular, elastic walls to withstand this pressure. Veins carry blood back to the heart at much lower pressure, so have thinner walls, and contain valves to prevent blood flowing backwards, since there is little pressure to keep it moving forward.',
 'This describes arteries and veins the wrong way round — arteries carry blood away from the heart, and veins carry blood back towards it.',
 'The wall structure differences directly relate to the very different blood pressures in arteries versus veins — this is functionally important, not incidental.',
 'Blood volume carried is not the reason veins have valves — it is because they carry blood at low pressure, so valves are needed to prevent blood flowing backwards.',
 'Arteries carry blood away from the heart at high pressure, so they have thick, muscular, and elastic walls to withstand and help maintain this pressure. Veins carry blood back to the heart at much lower pressure, so their walls are thinner; they also contain valves to prevent blood flowing backwards, since there is little pressure pushing the blood along.',
 'Arteries: thick walls for high pressure. Veins: valves prevent backflow at low pressure [1]',
 'ai_drafted', true, true),

('Biology','AQA','GCSE','Higher','Organisation','Plant Tissues','TO_BE_VERIFIED',2,
 'What are the roles of xylem and phloem tissue in a plant?',
 'Xylem transports water and minerals upward from the roots; phloem transports dissolved sugars (produced by photosynthesis) around the plant','Xylem transports sugars around the plant; phloem transports water and minerals from the roots','Both xylem and phloem transport only water, in opposite directions','Xylem and phloem are both involved only in photosynthesis, not transport','Not sure','a',
 'Correct — xylem tissue transports water and dissolved mineral ions from the roots upward through the plant, in one direction only. Phloem tissue transports dissolved sugars (produced by photosynthesis) from the leaves to other parts of the plant, in both directions, in a process called translocation.',
 'This swaps the roles of xylem and phloem — xylem carries water and minerals, while phloem carries dissolved sugars, not the other way around.',
 'Xylem and phloem carry different substances (water/minerals versus dissolved sugars) — they are not both simply carrying water.',
 'Xylem and phloem are transport tissues, not sites of photosynthesis themselves — photosynthesis occurs mainly in the leaf''s mesophyll cells, and its products are then transported by the phloem.',
 'Xylem tissue is made of dead, hollow cells that transport water and dissolved mineral ions from the roots upward through the plant, in one direction. Phloem tissue is made of living cells that transport dissolved sugars produced by photosynthesis from the leaves to other parts of the plant (such as roots and growing tissue) in a process called translocation, which can occur in either direction.',
 'Xylem: water/minerals up from roots. Phloem: sugars from leaves, both directions [1]',
 'ai_drafted', true, true),

-- Topic: Infection and Response
('Biology','AQA','GCSE','Higher','Infection and Response','Pathogens','TO_BE_VERIFIED',1,
 'Which of these is a type of pathogen that can cause disease?',
 'A red blood cell','A virus','An enzyme','A hormone','Not sure','b',
 'A red blood cell is a normal part of the human body, not a pathogen — it does not cause disease.',
 'Correct — a virus is a type of pathogen: a microorganism that can cause infectious disease, alongside bacteria, fungi, and protists.',
 'An enzyme is a biological catalyst produced by cells, not a disease-causing organism.',
 'A hormone is a chemical messenger produced by the body, not a disease-causing organism.',
 'Pathogens are microorganisms that cause infectious disease. The four main types studied at GCSE are bacteria, viruses, fungi, and protists. A virus is a pathogen that can only reproduce inside living host cells, often damaging them in the process.',
 'A virus is a type of pathogen [1]',
 'ai_drafted', true, true),

('Biology','AQA','GCSE','Higher','Infection and Response','Vaccination','TO_BE_VERIFIED',3,
 'How does vaccination protect a person against a specific disease?',
 'It introduces antibiotics directly into the bloodstream to kill any future pathogens','It introduces a small, safe amount of dead or inactive pathogen, causing white blood cells to produce antibodies and "remember" that pathogen','It removes the person''s ability to catch any disease at all','It directly destroys the pathogen''s DNA before infection can occur','Not sure','b',
 'Vaccines do not contain antibiotics — antibiotics only work against bacteria, and vaccination works differently, by training the immune system itself.',
 'Correct — a vaccine contains a small, safe amount of a dead or inactive form of a pathogen (or parts of it). This causes white blood cells to produce antibodies specific to that pathogen and creates memory cells, so if the real pathogen is encountered later, the immune system can respond much more quickly, often before the person becomes ill.',
 'Vaccination protects against the specific disease the vaccine targets, not against all diseases in general.',
 'Vaccination works by stimulating the person''s own immune system to produce antibodies, not by directly destroying the pathogen''s DNA.',
 'A vaccine contains a small, safe amount of a dead or inactivated pathogen (or a harmless part of it). This stimulates white blood cells to produce antibodies against that specific pathogen, and creates long-lasting memory cells. If the person is later exposed to the real, live pathogen, their immune system recognises it and can produce antibodies rapidly, usually preventing illness.',
 'Vaccine stimulates antibody production and memory cells for a specific pathogen [1]',
 'ai_drafted', true, true),

('Biology','AQA','GCSE','Higher','Infection and Response','Antibiotics','TO_BE_VERIFIED',2,
 'Why are antibiotics effective against bacterial infections but not against viral infections such as the common cold?',
 'Antibiotics target processes specific to bacterial cells, which viruses do not have, since viruses are not living cells','Viruses are much larger than bacteria, so antibiotics cannot physically reach them','Antibiotics only work on infections in the digestive system','Bacteria are always harmless, so treating them is unnecessary','Not sure','a',
 'Correct — antibiotics work by targeting specific structures or processes found in bacterial cells (such as their cell walls) that human and viral particles do not have. Viruses are not living cells and reproduce inside a host''s own cells using the host''s machinery, so there is no equivalent bacterial-specific target for antibiotics to act on.',
 'This is not about size or physical reach — antibiotics are ineffective against viruses because viruses lack the specific cellular structures and processes that antibiotics are designed to disrupt.',
 'Antibiotics can treat bacterial infections throughout the body, not only in the digestive system — the reason they don''t work on viruses is about the biological target, not the location of infection.',
 'Bacteria are not always harmless — many bacterial species cause serious disease, which is exactly why antibiotics were developed to treat bacterial infections.',
 'Antibiotics work by disrupting processes specific to bacterial cells, such as bacterial cell wall construction, which are different from human cell processes. Viruses are not cells at all — they reproduce by inserting their genetic material into a host''s own cells and hijacking the host''s machinery — so there is no equivalent bacterial target for antibiotics to act on, which is why antibiotics are ineffective against viral infections.',
 'Antibiotics target bacteria-specific processes; viruses lack these targets [1]',
 'ai_drafted', true, true),

('Biology','AQA','GCSE','Higher','Infection and Response','Spread of Disease','TO_BE_VERIFIED',2,
 'Which of the following is a way that many respiratory pathogens, such as the flu virus, commonly spread between people?',
 'Direct transfer of genetic material through soil','Droplet infection — through coughing or sneezing, releasing pathogen-containing droplets into the air','Only through direct contact with an infected person''s blood','They cannot spread between people at all','Not sure','b',
 'Soil-based genetic transfer is not a recognised route by which respiratory pathogens like flu spread between people.',
 'Correct — many respiratory pathogens spread by droplet infection: when an infected person coughs or sneezes, tiny droplets containing the pathogen are released into the air and can be inhaled by others nearby.',
 'While bloodborne transmission is a real route for some pathogens (such as certain viruses), it is not the typical way respiratory pathogens like flu spread — droplet infection through the air is far more common for these.',
 'Respiratory pathogens like the flu virus clearly do spread between people, which is why outbreaks and epidemics of flu occur regularly.',
 'Many pathogens, particularly those causing respiratory illnesses like flu and colds, spread by droplet infection. When an infected person coughs, sneezes, or even talks, tiny droplets of saliva or mucus containing the pathogen are released into the air, and can be breathed in by other people nearby, or land on surfaces that are then touched.',
 'Droplet infection spreads pathogens through coughing/sneezing [1]',
 'ai_drafted', true, true),

-- Topic: Bioenergetics
('Biology','AQA','GCSE','Higher','Bioenergetics','Photosynthesis','TO_BE_VERIFIED',1,
 'What are the raw materials needed for photosynthesis, and what are the products?',
 'Raw materials: glucose and oxygen. Products: carbon dioxide and water','Raw materials: carbon dioxide and water. Products: glucose and oxygen','Raw materials: carbon dioxide and oxygen. Products: glucose and water','Raw materials: nitrogen and water. Products: glucose and carbon dioxide','Not sure','b',
 'This has photosynthesis''s raw materials and products swapped — glucose and oxygen are the products, not the raw materials.',
 'Correct — photosynthesis takes in carbon dioxide and water (using light energy) and produces glucose and oxygen: 6CO2 + 6H2O -> C6H12O6 + 6O2.',
 'Oxygen is a product of photosynthesis, not a raw material taken in — it is carbon dioxide, not oxygen, that plants take in as a raw material.',
 'Nitrogen is not a raw material for photosynthesis — the raw materials are carbon dioxide and water, using light energy captured by chlorophyll.',
 'Photosynthesis is the process by which plants use light energy to convert carbon dioxide and water into glucose, releasing oxygen as a by-product: 6CO2 + 6H2O -> C6H12O6 + 6O2. This reaction takes place mainly in the chloroplasts of leaf cells, which contain the pigment chlorophyll to absorb light energy.',
 'Photosynthesis: CO2 + water -> glucose + oxygen (using light energy) [1]',
 'ai_drafted', true, true),

('Biology','AQA','GCSE','Higher','Bioenergetics','Limiting Factors','TO_BE_VERIFIED',3,
 'A plant''s rate of photosynthesis is being measured as light intensity increases. Initially the rate increases, but eventually it levels off even as light intensity keeps increasing. What does this levelling off suggest?',
 'The plant has stopped photosynthesising entirely','Light intensity is no longer the limiting factor; some other factor, such as carbon dioxide concentration or temperature, is now limiting the rate','The plant has run out of chlorophyll permanently','Photosynthesis rate always levels off regardless of any other conditions','Not sure','b',
 'A levelling-off rate means photosynthesis is continuing at a steady rate, not that it has stopped entirely.',
 'Correct — once increasing light intensity no longer increases the rate of photosynthesis, some other factor (commonly carbon dioxide concentration or temperature) must now be limiting the rate instead — this is called a limiting factor.',
 'Levelling off does not indicate a permanent loss of chlorophyll — it indicates that a different factor besides light has become the constraint on the reaction rate.',
 'The specific factor causing the plateau (light, CO2, or temperature) depends on the actual growing conditions — it is not simply an automatic, unconditional levelling-off regardless of the environment.',
 'When one factor (such as light intensity) is increased and the rate of photosynthesis stops increasing and levels off, it means that factor is no longer limiting — some other factor, most commonly carbon dioxide concentration or temperature, has now become the limiting factor holding the rate steady, regardless of how much further light intensity increases.',
 'Levelling off indicates a different factor (e.g. CO2 or temperature) is now limiting [1]',
 'ai_drafted', true, true),

('Biology','AQA','GCSE','Higher','Bioenergetics','Aerobic Respiration','TO_BE_VERIFIED',2,
 'What is the word equation for aerobic respiration?',
 'Glucose + oxygen -> carbon dioxide + water','Carbon dioxide + water -> glucose + oxygen','Glucose -> lactic acid','Glucose -> ethanol + carbon dioxide','Not sure','a',
 'Correct — aerobic respiration is the process by which cells release energy from glucose using oxygen, producing carbon dioxide and water as waste products: glucose + oxygen -> carbon dioxide + water.',
 'This is the word equation for photosynthesis, not aerobic respiration — the reactants and products are the reverse of respiration.',
 'This describes anaerobic respiration in animal cells (producing lactic acid), not aerobic respiration, which uses oxygen and produces carbon dioxide and water.',
 'This describes anaerobic respiration in yeast/plant cells (producing ethanol and carbon dioxide), not aerobic respiration.',
 'Aerobic respiration is the process that releases energy from glucose using oxygen, and takes place continuously in living cells, mostly in the mitochondria. The word equation is: glucose + oxygen -> carbon dioxide + water. This is the most efficient way cells release energy for processes such as movement, growth, and keeping warm.',
 'Aerobic respiration: glucose + oxygen -> carbon dioxide + water [1]',
 'ai_drafted', true, true),

('Biology','AQA','GCSE','Higher','Bioenergetics','Anaerobic Respiration','TO_BE_VERIFIED',3,
 'During intense exercise, muscle cells may not receive oxygen fast enough to meet their energy demands, so they respire anaerobically. What substance builds up in the muscles as a result, and what effect does this have?',
 'Ethanol builds up, causing the muscles to relax completely','Lactic acid builds up, which can cause muscle fatigue and cramp','Glucose builds up, providing extra energy with no downside','Oxygen builds up, improving muscle performance further','Not sure','b',
 'Ethanol is produced by anaerobic respiration in yeast and some plant cells, not in human muscle cells, which produce lactic acid instead.',
 'Correct — in human muscle cells, anaerobic respiration produces lactic acid as a by-product. As lactic acid builds up, it can cause muscle fatigue and cramp, and it also creates an "oxygen debt" that must be repaid afterwards through continued heavy breathing.',
 'Anaerobic respiration releases much less energy per glucose molecule than aerobic respiration, and the lactic acid produced causes fatigue — it does not simply provide "extra energy with no downside."',
 'Oxygen does not build up during anaerobic respiration — the whole reason cells respire anaerobically is because there is not enough oxygen available to meet demand.',
 'When muscle cells cannot get enough oxygen during intense exercise, they respire anaerobically, releasing energy from glucose without using oxygen. This produces lactic acid as a by-product (rather than carbon dioxide and water). Lactic acid builds up in the muscles, contributing to muscle fatigue and cramp, and creates an "oxygen debt" that the body repays afterwards by continuing to breathe heavily to break down the lactic acid.',
 'Anaerobic respiration in muscles produces lactic acid, causing fatigue [1]',
 'ai_drafted', true, true),

-- Topic: Homeostasis and Response
('Biology','AQA','GCSE','Higher','Homeostasis and Response','The Nervous System','TO_BE_VERIFIED',2,
 'What is the general pathway that information follows in a simple nervous system response, from detecting a stimulus to producing a response?',
 'Effector -> receptor -> coordinator -> stimulus','Stimulus -> receptor -> coordinator (CNS) -> effector -> response','Response -> stimulus -> receptor -> effector','Stimulus -> effector -> receptor -> coordinator','Not sure','b',
 'This lists the pathway components in reverse order, starting from the effector rather than ending with it.',
 'Correct — a stimulus is detected by a receptor, which sends information (via a sensory neurone) to a coordinator (part of the central nervous system, i.e. the brain or spinal cord), which sends instructions (via a motor neurone) to an effector (a muscle or gland), which brings about the response.',
 'This starts with "response," which should come at the end of the pathway, after the effector has acted, not at the beginning.',
 'This has the effector and receptor in the wrong order — the receptor detects the stimulus first, before any signal reaches the coordinator or effector.',
 'The general pathway in a nervous system response is: stimulus -> receptor (detects the stimulus) -> coordinator, part of the central nervous system, i.e. brain or spinal cord (processes the information and decides on a response) -> effector, a muscle or gland (carries out the response) -> response.',
 'Pathway: stimulus -> receptor -> coordinator (CNS) -> effector -> response [1]',
 'ai_drafted', true, true),

('Biology','AQA','GCSE','Higher','Homeostasis and Response','Blood Glucose Control','TO_BE_VERIFIED',3,
 'After eating a meal, blood glucose concentration rises. How does the body respond to bring it back down to normal?',
 'The pancreas releases glucagon, which converts glycogen into glucose','The pancreas releases insulin, which causes cells (especially in the liver) to take up glucose from the blood and store it as glycogen','The kidneys filter out all the glucose and remove it from the body permanently','The liver stops producing glycogen entirely','Not sure','b',
 'Glucagon has the opposite effect — it is released when blood glucose is too LOW, causing glycogen to be converted back into glucose, which would raise blood glucose further, not lower it.',
 'Correct — when blood glucose rises after eating, the pancreas releases the hormone insulin. Insulin causes cells, especially liver cells, to take up glucose from the blood and store it as glycogen, lowering blood glucose concentration back towards normal.',
 'The kidneys are not the primary organs responsible for regulating blood glucose concentration under normal conditions — that role belongs to the pancreas, liver, and hormones insulin and glucagon.',
 'It is not that glycogen production stops — insulin actually promotes the conversion of excess glucose into glycogen for storage, which is the opposite of stopping glycogen production.',
 'Blood glucose concentration is controlled by hormones from the pancreas. When blood glucose rises (such as after eating), the pancreas releases insulin, which causes cells throughout the body, particularly in the liver, to take up glucose from the blood and convert it into glycogen for storage, bringing blood glucose back down towards its normal level.',
 'Insulin causes glucose uptake and storage as glycogen, lowering blood glucose [1]',
 'ai_drafted', true, true),

('Biology','AQA','GCSE','Higher','Homeostasis and Response','The Menstrual Cycle','TO_BE_VERIFIED',3,
 'Which hormone, released in the middle of the menstrual cycle, triggers ovulation (the release of an egg from the ovary)?',
 'Progesterone','Follicle-stimulating hormone (FSH), released continuously throughout the cycle','A surge of luteinising hormone (LH)','Oestrogen, at consistently low levels throughout the cycle','Not sure','c',
 'Progesterone maintains the uterus lining after ovulation, but it is not the hormone that directly triggers ovulation itself.',
 'FSH stimulates the maturation of an egg in the ovary earlier in the cycle, but it is a surge in a different hormone, LH, that actually triggers the release of the egg.',
 'Correct — a surge in luteinising hormone (LH) around the middle of the menstrual cycle triggers ovulation, causing the mature egg to be released from the ovary.',
 'Oestrogen levels rise (not stay consistently low) in the lead-up to ovulation, and this rise helps trigger the LH surge that then causes ovulation.',
 'The menstrual cycle is controlled by several hormones. FSH causes an egg to mature in the ovary and stimulates oestrogen release. Rising oestrogen levels trigger a surge in luteinising hormone (LH) around day 14 of a typical cycle, and this LH surge is what triggers ovulation — the release of the mature egg from the ovary.',
 'LH surge triggers ovulation [1]',
 'ai_drafted', true, true),

('Biology','AQA','GCSE','Higher','Homeostasis and Response','Reflex Arc','TO_BE_VERIFIED',2,
 'Why are reflex actions, such as pulling your hand away from something hot, faster than a considered, voluntary response?',
 'Reflex actions do not involve the nervous system at all','The pathway (reflex arc) bypasses conscious processing in the brain, going directly from sensory neurone to relay neurone to motor neurone, often via the spinal cord','Reflex actions only occur in the eyes, which naturally respond faster than other body parts','Reflex actions always involve more neurones than voluntary responses, making them faster','Not sure','b',
 'Reflex actions do involve the nervous system — they use a specific, rapid pathway of neurones, just without requiring conscious thought.',
 'Correct — in a reflex arc, the signal passes from a sensory neurone to a relay neurone, then to a motor neurone, often via the spinal cord, without needing to travel to the brain for conscious decision-making. This shorter pathway means the response happens much faster than a considered, voluntary action.',
 'Reflex actions are not limited to the eyes — many reflexes involve other parts of the body, such as the hand-withdrawal reflex from a hot object.',
 'Reflex arcs typically involve fewer neurones and a shorter pathway than voluntary responses (which involve conscious processing in the brain), and it is this shorter pathway, not a larger number of neurones, that makes them faster.',
 'A reflex action follows a reflex arc: a stimulus is detected by a receptor, and the signal passes along a sensory neurone to a relay neurone (often in the spinal cord), then directly to a motor neurone, which causes an effector (a muscle) to respond. Because this pathway bypasses the need for conscious processing in the brain, reflex responses happen much faster than voluntary, considered responses.',
 'Reflex arc bypasses conscious brain processing, making it faster [1]',
 'ai_drafted', true, true),

-- Topic: Inheritance, Variation and Evolution
('Biology','AQA','GCSE','Higher','Inheritance, Variation and Evolution','DNA Structure','TO_BE_VERIFIED',2,
 'What shape does a molecule of DNA form, and where in the cell is most of it found?',
 'A single straight strand, found in the cytoplasm','A double helix, found mainly in the nucleus of the cell','A flat sheet, found in the mitochondria only','A branching tree shape, found in the cell membrane','Not sure','b',
 'DNA is not a single straight strand — it is a double helix, made of two strands wound around each other, and it is not found mainly in the cytoplasm.',
 'Correct — DNA is a polymer made of two strands coiled together to form a double helix. In eukaryotic cells (such as human cells), most DNA is found in the nucleus, organised into structures called chromosomes.',
 'DNA does not form a flat sheet shape, and while mitochondria do contain a small amount of their own DNA, most of a cell''s DNA is found in the nucleus, not exclusively in the mitochondria.',
 'DNA does not form a branching tree shape, and it is not found in the cell membrane — it is located mainly in the nucleus.',
 'DNA (deoxyribonucleic acid) is a polymer made of two strands that coil around each other to form a double helix. In a eukaryotic cell such as a human cell, most of the cell''s DNA is found in the nucleus, tightly coiled into structures called chromosomes.',
 'DNA forms a double helix, found mainly in the nucleus [1]',
 'ai_drafted', true, true),

('Biology','AQA','GCSE','Higher','Inheritance, Variation and Evolution','Monohybrid Crosses','TO_BE_VERIFIED',3,
 'In pea plants, the allele for tall stems (T) is dominant over the allele for short stems (t). If two heterozygous tall plants (Tt) are crossed, what proportion of their offspring would be expected to be short?',
 '0% (none)','25% (1 in 4)','50% (1 in 2)','100% (all of them)','Not sure','b',
 'Some offspring are expected to be short — heterozygous parents (Tt x Tt) can produce homozygous recessive (tt, short) offspring, so it is not zero.',
 'Correct — crossing Tt x Tt gives a genotype ratio of 1 TT : 2 Tt : 1 tt across the offspring (shown clearly on a Punnett square). Only the tt genotype produces the short phenotype, since t is recessive, so 1 in 4 (25%) of offspring are expected to be short.',
 'Half the offspring being short would only occur in different specific crosses (such as Tt x tt), not in a Tt x Tt cross, which gives 25% short offspring.',
 'Not all offspring will be short — three-quarters of the offspring (TT and Tt genotypes) will show the dominant tall phenotype; only the tt genotype (1 in 4) will be short.',
 'A Punnett square for Tt x Tt gives the genotype combinations TT, Tt, Tt, and tt among the four possible offspring combinations — a ratio of 1 TT : 2 Tt : 1 tt. Since T (tall) is dominant, both TT and Tt genotypes show the tall phenotype (3 out of 4, or 75%). Only the tt genotype shows the recessive short phenotype, which is 1 out of 4, or 25%, of the offspring.',
 'Tt x Tt gives 1:2:1 genotype ratio; 25% are tt (short phenotype) [1]',
 'ai_drafted', true, true),

('Biology','AQA','GCSE','Higher','Inheritance, Variation and Evolution','Natural Selection','TO_BE_VERIFIED',3,
 'A population of insects shows variation in colour. A change in the environment makes darker insects harder for predators to spot. Over many generations, how would you expect this to affect the population, and why?',
 'The proportion of darker insects would increase, because they are more likely to survive and reproduce, passing on the alleles for dark colour','The population would become entirely uniform in a single generation, with no variation at all','Insects would consciously change their own colour to survive better','The proportion of lighter insects would increase, since predators focus more on darker prey','Not sure','a',
 'Correct — this is natural selection in action: darker insects are less likely to be eaten, so are more likely to survive and reproduce, passing on the alleles for dark colouring to their offspring. Over many generations, the proportion of the population with the advantageous darker colouring is expected to increase.',
 'Natural selection acts gradually over many generations, not by producing complete uniformity within a single generation — some variation typically persists.',
 'Organisms cannot consciously choose to change their own genetically-determined traits — natural selection works because individuals with an advantageous inherited variation survive and reproduce more successfully, not through deliberate change.',
 'This has the selection pressure backwards — since predators find it harder to spot darker insects (not lighter ones), it is the darker insects that would be expected to survive better and increase in proportion, not the lighter ones.',
 'This scenario describes natural selection: within the population, there is already variation in colour. Because darker insects are harder for predators to spot, they are more likely to survive long enough to reproduce, passing their alleles for dark colouring on to their offspring. Over many generations, since more of the surviving, reproducing insects are dark, the proportion of the population with dark colouring is expected to increase.',
 'Advantageous trait (dark colour) increases in frequency via natural selection over generations [1]',
 'ai_drafted', true, true),

('Biology','AQA','GCSE','Higher','Inheritance, Variation and Evolution','Evolution','TO_BE_VERIFIED',2,
 'What is meant by "evolution" in a biological sense?',
 'A sudden change that occurs within a single organism''s lifetime','The gradual change in the inherited characteristics of a population over many generations','The process by which an individual organism learns new skills','A change in an organism''s environment, unrelated to its genes','Not sure','b',
 'Evolution does not describe a change within a single organism''s own lifetime — an individual organism''s genes do not change through evolution; it is populations, over generations, that evolve.',
 'Correct — evolution is the gradual change in the inherited characteristics of a population over many generations, arising through processes such as natural selection acting on genetic variation within the population.',
 'Evolution is not about an individual learning new skills during its lifetime — those skills are not passed on genetically, and learning is a different process entirely from evolutionary, inherited change.',
 'Evolution specifically concerns changes in a population''s inherited (genetic) characteristics, not simply environmental change on its own — though environmental change can act as a selection pressure driving evolution.',
 'Evolution is the gradual change in the inherited characteristics of a population of organisms over many generations. It occurs through processes such as natural selection, where individuals with characteristics better suited to their environment are more likely to survive and reproduce, passing those advantageous inherited characteristics on to future generations.',
 'Evolution = gradual change in inherited characteristics of a population over generations [1]',
 'ai_drafted', true, true),

-- Topic: Ecology
('Biology','AQA','GCSE','Higher','Ecology','Food Chains','TO_BE_VERIFIED',1,
 'In the food chain "grass -> rabbit -> fox," what role does the rabbit play?',
 'Producer','Primary consumer','Secondary consumer','Decomposer','Not sure','b',
 'A producer is an organism, typically a plant, that makes its own food by photosynthesis — the grass is the producer in this food chain, not the rabbit.',
 'Correct — the rabbit eats the grass (a producer) directly, making it a primary consumer. Primary consumers are always the organisms that feed directly on producers.',
 'A secondary consumer eats a primary consumer — that role belongs to the fox in this food chain, which eats the rabbit, not to the rabbit itself.',
 'A decomposer breaks down dead organic matter — the rabbit is a living consumer in this food chain, not a decomposer.',
 'In a food chain, the producer (usually a green plant, here grass) makes its own food by photosynthesis. The primary consumer is the organism that eats the producer directly — here, the rabbit, which eats grass. The secondary consumer eats the primary consumer — here, the fox, which eats the rabbit.',
 'Rabbit is the primary consumer, eating the producer (grass) [1]',
 'ai_drafted', true, true),

('Biology','AQA','GCSE','Higher','Ecology','The Carbon Cycle','TO_BE_VERIFIED',2,
 'Which process removes carbon dioxide from the atmosphere and is carried out by plants?',
 'Respiration','Combustion','Photosynthesis','Decomposition','Not sure','c',
 'Respiration releases carbon dioxide into the atmosphere (as a waste product of releasing energy from glucose), rather than removing it.',
 'Combustion (burning) releases carbon dioxide into the atmosphere, particularly from burning fossil fuels — it does not remove carbon dioxide.',
 'Correct — photosynthesis removes carbon dioxide from the atmosphere, using it (along with water and light energy) to produce glucose, which becomes part of the plant''s biomass.',
 'Decomposition releases carbon dioxide back into the atmosphere as decomposers break down dead organic matter and respire — it does not remove carbon dioxide.',
 'In the carbon cycle, photosynthesis is the main process that removes carbon dioxide from the atmosphere: plants use carbon dioxide, water, and light energy to produce glucose, incorporating carbon into their biomass. Processes such as respiration, combustion, and decomposition all return carbon dioxide to the atmosphere.',
 'Photosynthesis removes CO2 from the atmosphere [1]',
 'ai_drafted', true, true),

('Biology','AQA','GCSE','Higher','Ecology','Biodiversity','TO_BE_VERIFIED',2,
 'What does "biodiversity" mean, and why is maintaining a high level of it generally considered important?',
 'Biodiversity is the total number of individual organisms in one specific species; high biodiversity means one species has a very large population','Biodiversity is the variety of different species living in an area; high biodiversity helps maintain stable, resilient ecosystems','Biodiversity refers only to plant species, ignoring animals, fungi, and microorganisms','Biodiversity always decreases naturally over time and cannot be maintained by human action','Not sure','b',
 'Biodiversity is about the variety of different species present, not simply the population size of one particular species.',
 'Correct — biodiversity is the variety of different species living in an ecosystem or area. High biodiversity generally supports greater ecosystem stability and resilience, since ecosystems with more species tend to be better able to withstand environmental changes or the loss of any single species.',
 'Biodiversity considers the full range of living organisms in an area, including animals, fungi, and microorganisms, not plants alone.',
 'Biodiversity is significantly affected by human activity (both positively and negatively) — conservation efforts, protected areas, and reduced habitat destruction can help maintain or increase biodiversity, so it is not simply an inevitable, uncontrollable decline.',
 'Biodiversity is the variety of different species of organisms living within an ecosystem or a given area. Maintaining high biodiversity is generally considered important because ecosystems with a greater variety of species tend to be more stable and resilient — better able to cope with environmental changes, disease, or the loss of any one species, since other species can often fill similar ecological roles.',
 'Biodiversity = variety of species; supports ecosystem stability and resilience [1]',
 'ai_drafted', true, true),

('Biology','AQA','GCSE','Higher','Ecology','Abiotic and Biotic Factors','TO_BE_VERIFIED',2,
 'A population of fish in a lake declines sharply after a factory begins discharging warm water into the lake, raising its temperature. Is this an example of an abiotic or a biotic factor affecting the population, and why?',
 'Biotic, because it involves a living organism (the fish)','Abiotic, because temperature is a non-living, physical/chemical factor affecting the organisms in the ecosystem','Neither — factory activity cannot be classified as either type of factor','Biotic, because factories are considered living systems in ecology','Not sure','b',
 'The fish being a living organism does not make the CAUSE of the change biotic — it is the temperature change itself, a non-living physical factor, that is being classified here.',
 'Correct — abiotic factors are non-living, physical or chemical factors that affect organisms in an ecosystem, such as temperature, light intensity, pH, and moisture level. A rise in water temperature is a classic example of an abiotic factor.',
 'Environmental changes caused by human activity, such as a factory discharging warm water, can and do affect abiotic factors (like temperature) within ecosystems — this is a well-established, classifiable ecological factor.',
 'A factory is not a living organism and is not considered a "biotic" factor in ecology — biotic factors specifically refer to living organisms (such as predators, competitors, or pathogens) within an ecosystem.',
 'Ecological factors affecting organisms are classified as either biotic (living factors, such as predation, competition, and disease) or abiotic (non-living, physical or chemical factors, such as temperature, light intensity, and pH). A rise in water temperature — even though it is caused by human/factory activity — is an abiotic factor, since temperature itself is a non-living, physical property of the environment.',
 'Temperature is an abiotic (non-living) factor [1]',
 'ai_drafted', true, true);
