-- Diagnostic Stage 2 — Mathematics draft questions (maths_batch_02, 18 questions).
-- Generated by supabase/content/build.js from supabase/content/maths_batch_02.js
-- (batch drafted-2026-09-27-maths-batch-02-numeric). source is always 'ai_drafted': the live
-- diagnostic_questions_source_check constraint allows no other new value.
--
-- These are DRAFTS: inserted as review_status 'draft' (validated false) and
-- never served until a person approves each one on the review page:
-- https://www.inspireacademic.org/teacher/question-review.html
-- Safe to re-run: a question already in the bank is skipped.
--
-- Needs supabase/diagnostic_questions_review.sql first, and
-- supabase/diagnostic_question_types.sql (this batch has typed-number questions).
-- Run in the LIVE project only:
-- https://supabase.com/dashboard/project/ygtsrdwoikqnrbexjrtl/sql/new

begin;

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Mathematics$t$, $t$AQA$t$, 'GCSE', $t$Both$t$, $t$Fractions, decimals and percentages$t$, $t$Percentage of an Amount$t$, $t$aqa-ma-fh-fractions-decimals-percentages$t$, 1,
  $t$A school bag costs GH₵ 240. Work out 15% of GH₵ 240, in cedis.$t$,
  null, null, null, null, 'Not sure', null,
  null, null, null, null,
  $t$10% of 240 is 24 and 5% is 12, so 15% \(= 24 + 12 = 36\) cedis.$t$,
  'ai_drafted', false, true, 'draft', 'numeric', $t${"value":36,"wrong":[{"value":16,"misconception":"This divides 240 by 15. 15% means \\(\\tfrac{15}{100}\\): \\(0.15 \\times 240 = 36\\)."},{"value":204,"misconception":"That is the price after taking 15% off. 15% of 240 is \\(0.15 \\times 240 = 36\\)."},{"value":3600,"misconception":"This multiplies by 15 without dividing by 100: \\(\\tfrac{15}{100} \\times 240 = 36\\)."}]}$t$::jsonb, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Mathematics$t$ and question_text = $t$A school bag costs GH₵ 240. Work out 15% of GH₵ 240, in cedis.$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Mathematics$t$, $t$AQA$t$, 'GCSE', $t$Both$t$, $t$Ratio, proportion and rates of change$t$, $t$Sharing in a Ratio$t$, $t$aqa-ma-fh-ratio-proportion$t$, 2,
  $t$Chinedu and Ngozi share ₦45 000 in the ratio 2 : 3. How much does Ngozi get, in naira?$t$,
  null, null, null, null, 'Not sure', null,
  null, null, null, null,
  $t$There are \(2 + 3 = 5\) parts. One part \(= 45\,000 \div 5 = 9000\). Ngozi gets \(3 \times 9000 = 27\,000\) naira.$t$,
  'ai_drafted', false, true, 'draft', 'numeric', $t${"value":27000,"wrong":[{"value":18000,"misconception":"That is Chinedu's share (2 parts). Ngozi gets 3 parts: \\(45\\,000 \\div 5 = 9000\\) per part, so \\(3 \\times 9000 = 27\\,000\\)."},{"value":15000,"misconception":"This divides by 3, as if there were 3 parts in total. There are \\(2 + 3 = 5\\) parts: \\(3 \\times 9000 = 27\\,000\\)."},{"value":22500,"misconception":"This splits the money equally. In the ratio 2 : 3, Ngozi gets \\(\\tfrac{3}{5}\\) of it: \\(27\\,000\\)."}]}$t$::jsonb, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Mathematics$t$ and question_text = $t$Chinedu and Ngozi share ₦45 000 in the ratio 2 : 3. How much does Ngozi get, in naira?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Mathematics$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Ratio, proportion and rates of change$t$, $t$Compound Interest$t$, $t$aqa-ma-fh-ratio-proportion$t$, 4,
  $t$Efua saves GH₵ 5000 at 4% compound interest per year. How much is in the account after 3 years? Give your answer to the nearest pesewa (2 decimal places).$t$,
  null, null, null, null, 'Not sure', null,
  null, null, null, null,
  $t$Each year the amount is multiplied by 1.04: \(5000 \times 1.04^{3} = 5000 \times 1.124864 = 5624.32\) cedis.$t$,
  'ai_drafted', false, true, 'draft', 'numeric', $t${"value":5624.32,"tolerance":0.0005,"wrong":[{"value":5600,"misconception":"This is simple interest (GH₵ 200 each year). Compound interest adds interest on the interest: \\(5000 \\times 1.04^{3} = 5624.32\\)."},{"value":5408,"misconception":"That is after 2 years. After 3 years: \\(5000 \\times 1.04^{3} = 5624.32\\)."},{"value":624.32,"misconception":"That is the interest earned. The amount in the account is \\(5000 + 624.32 = 5624.32\\)."}]}$t$::jsonb, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Mathematics$t$ and question_text = $t$Efua saves GH₵ 5000 at 4% compound interest per year. How much is in the account after 3 years? Give your answer to the nearest pesewa (2 decimal places).$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Mathematics$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Fractions, decimals and percentages$t$, $t$Reverse Percentages$t$, $t$aqa-ma-fh-fractions-decimals-percentages$t$, 3,
  $t$After a 25% increase, the price of a bag of rice is GH₵ 150. What was the price before the increase, in cedis?$t$,
  null, null, null, null, 'Not sure', null,
  null, null, null, null,
  $t$The new price is 125% of the old one: old price \(= 150 \div 1.25 = 120\) cedis. Check: \(120 \times 1.25 = 150\).$t$,
  'ai_drafted', false, true, 'draft', 'numeric', $t${"value":120,"wrong":[{"value":112.5,"misconception":"This takes 25% off the new price. GH₵ 150 is 125% of the old price, so divide by 1.25: \\(150 \\div 1.25 = 120\\)."},{"value":187.5,"misconception":"This adds another 25%. Undo the increase by dividing by 1.25: \\(150 \\div 1.25 = 120\\)."},{"value":125,"misconception":"This subtracts 25 cedis. The increase was 25% of the old price: \\(150 \\div 1.25 = 120\\)."}]}$t$::jsonb, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Mathematics$t$ and question_text = $t$After a 25% increase, the price of a bag of rice is GH₵ 150. What was the price before the increase, in cedis?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Mathematics$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Fractions, decimals and percentages$t$, $t$Percentage Change$t$, $t$aqa-ma-fh-fractions-decimals-percentages$t$, 3,
  $t$The population of a town near Tamale grew from 36 000 to 45 000. What is the percentage increase?$t$,
  null, null, null, null, 'Not sure', null,
  null, null, null, null,
  $t$Increase \(= 45\,000 - 36\,000 = 9000\). Percentage increase \(= \dfrac{9000}{36\,000} \times 100 = 25\%\).$t$,
  'ai_drafted', false, true, 'draft', 'numeric', $t${"value":25,"wrong":[{"value":20,"misconception":"This divides the increase by the new population. Divide by the original: \\(\\dfrac{9000}{36\\,000} \\times 100 = 25\\%\\)."},{"value":9000,"misconception":"9000 is the increase in people, not the percentage: \\(\\dfrac{9000}{36\\,000} \\times 100 = 25\\%\\)."},{"value":125,"misconception":"125% is the new population as a percentage of the old. The increase is \\(25\\%\\)."}]}$t$::jsonb, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Mathematics$t$ and question_text = $t$The population of a town near Tamale grew from 36 000 to 45 000. What is the percentage increase?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Mathematics$t$, $t$AQA$t$, 'GCSE', $t$Both$t$, $t$Ratio, proportion and rates of change$t$, $t$Speed, Distance, Time$t$, $t$aqa-ma-fh-ratio-proportion$t$, 2,
  $t$A bus travels 250 km from Accra to Kumasi at an average speed of 62.5 km/h. How many hours does the journey take?$t$,
  null, null, null, null, 'Not sure', null,
  null, null, null, null,
  $t$Time \(= \dfrac{\text{distance}}{\text{speed}} = \dfrac{250}{62.5} = 4\) hours.$t$,
  'ai_drafted', false, true, 'draft', 'numeric', $t${"value":4,"wrong":[{"value":15625,"misconception":"This multiplies distance by speed. Time \\(= \\dfrac{\\text{distance}}{\\text{speed}} = \\dfrac{250}{62.5} = 4\\) hours."},{"value":0.25,"misconception":"This divides speed by distance. Time \\(= \\dfrac{250}{62.5} = 4\\) hours."}]}$t$::jsonb, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Mathematics$t$ and question_text = $t$A bus travels 250 km from Accra to Kumasi at an average speed of 62.5 km/h. How many hours does the journey take?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Mathematics$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Ratio, proportion and rates of change$t$, $t$Proportion to a Square$t$, $t$aqa-ma-fh-ratio-proportion$t$, 4,
  $t$\(y\) is directly proportional to \(x^{2}\). When \(x = 2\), \(y = 12\). Find \(y\) when \(x = 5\).$t$,
  null, null, null, null, 'Not sure', null,
  null, null, null, null,
  $t$\(y = kx^{2}\). From \(12 = k \times 4\), \(k = 3\). When \(x = 5\): \(y = 3 \times 25 = 75\).$t$,
  'ai_drafted', false, true, 'draft', 'numeric', $t${"value":75,"wrong":[{"value":30,"misconception":"That treats \\(y\\) as proportional to \\(x\\), not \\(x^{2}\\). \\(y = kx^{2}\\) with \\(k = 3\\): \\(y = 3 \\times 25 = 75\\)."},{"value":4.8,"misconception":"That is inverse proportion. Here \\(y = kx^{2}\\), \\(k = \\dfrac{12}{4} = 3\\), so \\(y = 75\\)."},{"value":300,"misconception":"This uses \\(k = 12\\) without dividing by \\(2^{2}\\). \\(k = \\dfrac{12}{4} = 3\\), so \\(y = 3 \\times 25 = 75\\)."}]}$t$::jsonb, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Mathematics$t$ and question_text = $t$\(y\) is directly proportional to \(x^{2}\). When \(x = 2\), \(y = 12\). Find \(y\) when \(x = 5\).$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Mathematics$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Powers, roots and standard form$t$, $t$Standard Form Division$t$, $t$aqa-ma-fh-powers-roots$t$, 4,
  $t$Work out \((6 \times 10^{5}) \div (3 \times 10^{-2})\). You can type your answer in standard form, for example 4e9.$t$,
  null, null, null, null, 'Not sure', null,
  null, null, null, null,
  $t$\(6 \div 3 = 2\) and \(10^{5} \div 10^{-2} = 10^{5 - (-2)} = 10^{7}\). The answer is \(2 \times 10^{7}\).$t$,
  'ai_drafted', false, true, 'draft', 'numeric', $t${"value":20000000,"wrong":[{"value":2000,"misconception":"This subtracts the powers as \\(5 - 2\\). Dividing subtracts them: \\(5 - (-2) = 7\\), so \\(2 \\times 10^{7}\\)."},{"value":18000,"misconception":"This multiplies instead of dividing. \\(6 \\div 3 = 2\\) and \\(10^{5} \\div 10^{-2} = 10^{7}\\): \\(2 \\times 10^{7}\\)."}]}$t$::jsonb, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Mathematics$t$ and question_text = $t$Work out \((6 \times 10^{5}) \div (3 \times 10^{-2})\). You can type your answer in standard form, for example 4e9.$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Mathematics$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Powers, roots and standard form$t$, $t$Fractional Indices$t$, $t$aqa-ma-fh-powers-roots$t$, 4,
  $t$Evaluate \(8^{\frac{2}{3}}\).$t$,
  null, null, null, null, 'Not sure', null,
  null, null, null, null,
  $t$The denominator 3 means cube root and the numerator 2 means square: \(8^{\frac{2}{3}} = (\sqrt[3]{8})^{2} = 2^{2} = 4\).$t$,
  'ai_drafted', false, true, 'draft', 'numeric', $t${"value":4,"wrong":[{"value":5.333,"misconception":"This multiplies 8 by \\(\\tfrac{2}{3}\\). A fractional power means a root and a power: \\((\\sqrt[3]{8})^{2} = 2^{2} = 4\\)."},{"value":2,"misconception":"That is the cube root only. Then square it: \\(2^{2} = 4\\)."},{"value":64,"misconception":"That squares 8 without taking the cube root. \\(\\sqrt[3]{64} = 4\\), the same as \\((\\sqrt[3]{8})^{2}\\)."}]}$t$::jsonb, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Mathematics$t$ and question_text = $t$Evaluate \(8^{\frac{2}{3}}\).$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Mathematics$t$, $t$AQA$t$, 'GCSE', $t$Both$t$, $t$Equations and inequalities$t$, $t$Unknowns on Both Sides$t$, $t$aqa-ma-fh-algebra-equations$t$, 2,
  $t$Solve \(5x - 7 = 3x + 9\). What is \(x\)?$t$,
  null, null, null, null, 'Not sure', null,
  null, null, null, null,
  $t$Subtract \(3x\): \(2x - 7 = 9\). Add 7: \(2x = 16\). Divide by 2: \(x = 8\).$t$,
  'ai_drafted', false, true, 'draft', 'numeric', $t${"value":8,"wrong":[{"value":2,"misconception":"This adds \\(3x\\) to the left instead of subtracting it. \\(5x - 3x = 2x\\), and \\(9 + 7 = 16\\), so \\(x = 8\\)."},{"value":1,"misconception":"This subtracts 7 from 9 instead of adding. Moving \\(-7\\) across gives \\(+7\\): \\(2x = 16\\), \\(x = 8\\)."},{"value":16,"misconception":"\\(2x = 16\\), so divide by 2: \\(x = 8\\)."}]}$t$::jsonb, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Mathematics$t$ and question_text = $t$Solve \(5x - 7 = 3x + 9\). What is \(x\)?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Mathematics$t$, $t$AQA$t$, 'GCSE', $t$Both$t$, $t$Sequences$t$, $t$nth Term$t$, $t$aqa-ma-fh-algebra-sequences$t$, 2,
  $t$The sequence \(7, 10, 13, 16, \ldots\) continues in the same way. What is its 50th term?$t$,
  null, null, null, null, 'Not sure', null,
  null, null, null, null,
  $t$The difference is 3, so the \(n\)th term is \(3n + c\). With \(n = 1\): \(3 + c = 7\), \(c = 4\). The 50th term is \(3 \times 50 + 4 = 154\).$t$,
  'ai_drafted', false, true, 'draft', 'numeric', $t${"value":154,"wrong":[{"value":157,"misconception":"This uses \\(3n + 7\\). The first term is \\(3 \\times 1 + 4 = 7\\), so the \\(n\\)th term is \\(3n + 4\\): \\(3 \\times 50 + 4 = 154\\)."},{"value":350,"misconception":"This multiplies the first term by 50. The terms go up by 3: the \\(n\\)th term is \\(3n + 4\\), so the 50th is 154."},{"value":150,"misconception":"\\(3 \\times 50\\) is only part of it: the \\(n\\)th term is \\(3n + 4\\), so add 4 to get 154."}]}$t$::jsonb, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Mathematics$t$ and question_text = $t$The sequence \(7, 10, 13, 16, \ldots\) continues in the same way. What is its 50th term?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Mathematics$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Number — basics and operations$t$, $t$Bounds$t$, $t$aqa-ma-fh-number-basics$t$, 5,
  $t$A rectangle measures 6 cm by 4 cm, each measured to the nearest centimetre. What is the upper bound of its area, in cm²?$t$,
  null, null, null, null, 'Not sure', null,
  null, null, null, null,
  $t$To the nearest cm the upper bounds are 6.5 cm and 4.5 cm. Upper bound of the area \(= 6.5 \times 4.5 = 29.25\,\text{cm}^{2}\).$t$,
  'ai_drafted', false, true, 'draft', 'numeric', $t${"value":29.25,"wrong":[{"value":24,"misconception":"This uses the rounded measurements. The largest possible lengths are 6.5 cm and 4.5 cm: \\(6.5 \\times 4.5 = 29.25\\,\\text{cm}^{2}\\)."},{"value":19.25,"misconception":"That is the lower bound (\\(5.5 \\times 3.5\\)). The upper bound uses 6.5 and 4.5: \\(29.25\\,\\text{cm}^{2}\\)."},{"value":35,"misconception":"This adds a whole centimetre to each side. To the nearest cm, the bounds are \\(\\pm 0.5\\): \\(6.5 \\times 4.5 = 29.25\\,\\text{cm}^{2}\\)."}]}$t$::jsonb, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Mathematics$t$ and question_text = $t$A rectangle measures 6 cm by 4 cm, each measured to the nearest centimetre. What is the upper bound of its area, in cm²?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Mathematics$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Probability$t$, $t$Without Replacement$t$, $t$aqa-ma-fh-probability$t$, 4,
  $t$A bag has 3 red and 5 blue counters. Two counters are taken out without replacement. What is the probability that both are red? You can type a fraction, such as 2/9.$t$,
  null, null, null, null, 'Not sure', null,
  null, null, null, null,
  $t$\(P(\text{red, red}) = \tfrac{3}{8} \times \tfrac{2}{7} = \tfrac{6}{56} = \tfrac{3}{28} \approx 0.107\).$t$,
  'ai_drafted', false, true, 'draft', 'numeric', $t${"value":0.10714285714285714,"tolerance":0.01,"wrong":[{"value":0.140625,"misconception":"\\(\\tfrac{9}{64}\\) assumes the first counter is put back. Without replacement: \\(\\tfrac{3}{8} \\times \\tfrac{2}{7} = \\tfrac{6}{56} = \\tfrac{3}{28}\\)."},{"value":0.75,"misconception":"This adds the probabilities. For \"and\", multiply: \\(\\tfrac{3}{8} \\times \\tfrac{2}{7} = \\tfrac{3}{28}\\)."},{"value":0.09375,"misconception":"This forgets that there are only 7 counters left for the second pick: \\(\\tfrac{3}{8} \\times \\tfrac{2}{7} = \\tfrac{3}{28}\\)."}]}$t$::jsonb, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Mathematics$t$ and question_text = $t$A bag has 3 red and 5 blue counters. Two counters are taken out without replacement. What is the probability that both are red? You can type a fraction, such as 2/9.$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Mathematics$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Trigonometry$t$, $t$Finding a Side$t$, $t$aqa-ma-fh-trigonometry$t$, 3,
  $t$A 5 m ladder leans against a wall, making an angle of \(70^{\circ}\) with the ground. How high up the wall does it reach? Give your answer to 2 decimal places.$t$,
  null, null, null, null, 'Not sure', null,
  null, null, null, null,
  $t$The ladder is the hypotenuse and the height is opposite the angle: \(h = 5 \sin 70^{\circ} = 4.698\ldots \approx 4.70\,\text{m}\).$t$,
  'ai_drafted', false, true, 'draft', 'numeric', $t${"value":4.698,"tolerance":0.002,"wrong":[{"value":1.71,"misconception":"This uses cosine, which gives the distance along the ground. The height is opposite the \\(70^{\\circ}\\) angle: \\(5 \\sin 70^{\\circ} = 4.70\\,\\text{m}\\)."},{"value":13.74,"misconception":"This uses tangent. The ladder is the hypotenuse, so use sine: \\(5 \\sin 70^{\\circ} = 4.70\\,\\text{m}\\)."},{"value":5.32,"misconception":"This divides by \\(\\sin 70^{\\circ}\\). Height \\(= 5 \\times \\sin 70^{\\circ} = 4.70\\,\\text{m}\\)."}]}$t$::jsonb, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Mathematics$t$ and question_text = $t$A 5 m ladder leans against a wall, making an angle of \(70^{\circ}\) with the ground. How high up the wall does it reach? Give your answer to 2 decimal places.$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Mathematics$t$, $t$AQA$t$, 'GCSE', $t$Both$t$, $t$Trigonometry$t$, $t$Pythagoras' Theorem$t$, $t$aqa-ma-fh-trigonometry$t$, 2,
  $t$A right-angled triangle has shorter sides of 9 cm and 12 cm. How long is the hypotenuse, in cm?$t$,
  null, null, null, null, 'Not sure', null,
  null, null, null, null,
  $t$\(c^{2} = 9^{2} + 12^{2} = 81 + 144 = 225\), so \(c = \sqrt{225} = 15\,\text{cm}\).$t$,
  'ai_drafted', false, true, 'draft', 'numeric', $t${"value":15,"wrong":[{"value":21,"misconception":"This adds the sides. Pythagoras adds their squares: \\(\\sqrt{81 + 144} = \\sqrt{225} = 15\\)."},{"value":7.94,"misconception":"This subtracts the squares, which finds a shorter side. For the hypotenuse, add: \\(\\sqrt{81 + 144} = 15\\)."},{"value":225,"misconception":"225 is \\(c^{2}\\). Take the square root: \\(\\sqrt{225} = 15\\)."}]}$t$::jsonb, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Mathematics$t$ and question_text = $t$A right-angled triangle has shorter sides of 9 cm and 12 cm. How long is the hypotenuse, in cm?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Mathematics$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Graphs$t$, $t$Gradient$t$, $t$aqa-ma-fh-graphs$t$, 2,
  $t$What is the gradient of the straight line through \((1, 3)\) and \((5, 11)\)?$t$,
  null, null, null, null, 'Not sure', null,
  null, null, null, null,
  $t$Gradient \(= \dfrac{y_2 - y_1}{x_2 - x_1} = \dfrac{11 - 3}{5 - 1} = \dfrac{8}{4} = 2\).$t$,
  'ai_drafted', false, true, 'draft', 'numeric', $t${"value":2,"wrong":[{"value":0.5,"misconception":"This divides the change in \\(x\\) by the change in \\(y\\). Gradient \\(= \\dfrac{\\text{change in } y}{\\text{change in } x} = \\dfrac{11 - 3}{5 - 1} = 2\\)."},{"value":2.2,"misconception":"This divides one \\(y\\)-value by one \\(x\\)-value. Use the changes: \\(\\dfrac{11 - 3}{5 - 1} = \\dfrac{8}{4} = 2\\)."},{"value":8,"misconception":"8 is the change in \\(y\\). Divide by the change in \\(x\\) (4): gradient \\(= 2\\)."}]}$t$::jsonb, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Mathematics$t$ and question_text = $t$What is the gradient of the straight line through \((1, 3)\) and \((5, 11)\)?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Mathematics$t$, $t$AQA$t$, 'GCSE', $t$Higher$t$, $t$Perimeter, area, volume$t$, $t$Area of a Circle$t$, $t$aqa-ma-fh-geometry-measures$t$, 2,
  $t$A round cocoa-drying mat has a diameter of 3 m. What is its area, in m², to 1 decimal place?$t$,
  null, null, null, null, 'Not sure', null,
  null, null, null, null,
  $t$Radius \(= 1.5\,\text{m}\). Area \(= \pi r^{2} = \pi \times 1.5^{2} = 7.07\ldots \approx 7.1\,\text{m}^{2}\).$t$,
  'ai_drafted', false, true, 'draft', 'numeric', $t${"value":7.0686,"tolerance":0.01,"wrong":[{"value":28.27,"misconception":"This uses the diameter as the radius. The radius is \\(3 \\div 2 = 1.5\\,\\text{m}\\): \\(\\pi \\times 1.5^{2} = 7.1\\,\\text{m}^{2}\\)."},{"value":9.42,"misconception":"That is the circumference (\\(\\pi d\\)). Area \\(= \\pi r^{2} = \\pi \\times 1.5^{2} = 7.1\\,\\text{m}^{2}\\)."},{"value":4.71,"misconception":"This forgets to square the radius: \\(\\pi \\times 1.5^{2} = 7.1\\,\\text{m}^{2}\\)."}]}$t$::jsonb, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Mathematics$t$ and question_text = $t$A round cocoa-drying mat has a diameter of 3 m. What is its area, in m², to 1 decimal place?$t$);

insert into public.diagnostic_questions (
  subject, exam_board, level, tier, topic, subtopic, spec_slug, difficulty,
  question_text, option_a, option_b, option_c, option_d, option_e, correct_answer,
  misconception_a, misconception_b, misconception_c, misconception_d, explanation,
  source, validated, active, review_status, question_type, answer_spec, combined_eligible, context_region)
select $t$Mathematics$t$, $t$AQA$t$, 'GCSE', $t$Both$t$, $t$Number — basics and operations$t$, $t$Order of Operations$t$, $t$aqa-ma-fh-number-basics$t$, 1,
  $t$Work out \(20 - 3 \times (2 + 4)^{2}\).$t$,
  null, null, null, null, 'Not sure', null,
  null, null, null, null,
  $t$Brackets: \(2 + 4 = 6\). Powers: \(6^{2} = 36\). Multiply: \(3 \times 36 = 108\). Subtract: \(20 - 108 = -88\).$t$,
  'ai_drafted', false, true, 'draft', 'numeric', $t${"value":-88,"wrong":[{"value":612,"misconception":"This works left to right: \\(20 - 3 = 17\\) first. Brackets, then powers, then multiplication: \\(20 - 3 \\times 36 = 20 - 108 = -88\\)."},{"value":-304,"misconception":"This squares \\(3 \\times 6\\). The power only applies to the bracket: \\(6^{2} = 36\\), then \\(3 \\times 36 = 108\\), so \\(20 - 108 = -88\\)."},{"value":2,"misconception":"This multiplies the bracket by 3 without squaring it. \\((2 + 4)^{2} = 36\\), so \\(20 - 108 = -88\\)."}]}$t$::jsonb, true, null
where not exists (select 1 from public.diagnostic_questions where subject = $t$Mathematics$t$ and question_text = $t$Work out \(20 - 3 \times (2 + 4)^{2}\).$t$);

commit;

-- Check: drafts per subject (this batch adds 18 Mathematics drafts).
select subject, review_status, count(*) from public.diagnostic_questions
 where review_status = 'draft' group by 1, 2 order by 1;
