-- ================================================================
-- student_term_topics.sql
--
-- New table + storage bucket backing student/term-topics.html: a
-- student photographs (or uploads a photo of) their school's topic
-- schedule for the current term, so a teacher can see it on
-- teacher/teacher.html's Student Info card and teach in step with
-- what the student is actually covering at school right now.
--
-- Brand new table/bucket, so — unlike most of this folder's other
-- migrations — there's no drift to reverse-engineer and no existing
-- policy to narrow. RLS is written correctly from the start, reusing
-- get_teacher_students()/is_admin() exactly as
-- quiz_progress_streaks_teacher_access_scoping.sql and
-- assessment_attempts_teacher_access.sql already establish as this
-- schema's standard "teacher sees only their assigned students"
-- pattern — not reinvented here.
--
-- Run once in the Supabase SQL editor.
-- ================================================================

create table if not exists student_term_topics (
  id bigint generated by default as identity primary key,
  student_id uuid not null references profiles(id) on delete cascade,
  photo_url text not null,
  subject text check (subject is null or subject in ('Mathematics','Physics','Chemistry','Biology','Other')),
  note text,
  uploaded_at timestamptz not null default now()
);

create index if not exists student_term_topics_student_id_idx
  on student_term_topics(student_id);

alter table student_term_topics enable row level security;

-- Student manages their own uploads (insert/select/delete their own
-- rows). No update policy needed — a student replaces a stale photo
-- by deleting and re-uploading, not editing one in place.
create policy "student_term_topics_own_all"
  on student_term_topics for all
  to authenticated
  using (auth.uid() = student_id)
  with check (auth.uid() = student_id);

-- Staff view only — a teacher/admin never edits a student's own
-- upload, only refers to it.
create policy "student_term_topics_staff_select"
  on student_term_topics for select
  to authenticated
  using (
    is_admin()
    or exists (
      select 1 from get_teacher_students(auth.uid()) gts
      where gts.student_id = student_term_topics.student_id
    )
  );

-- ── Storage bucket ──────────────────────────────────────────────
-- Public bucket (same access model as the existing project-photos
-- bucket year6-project.html already uses): reads go through the
-- public URL and never touch RLS; writes are still policy-gated
-- below, restricted to a student's own folder (path prefix = their
-- own auth uid, matching year6-project.html's
-- `${currentUser.id}/${section}/...` convention).
insert into storage.buckets (id, name, public)
values ('term-topic-photos', 'term-topic-photos', true)
on conflict (id) do nothing;

create policy "term_topic_photos_owner_all"
  on storage.objects for all
  to authenticated
  using (bucket_id = 'term-topic-photos' and (storage.foldername(name))[1] = auth.uid()::text)
  with check (bucket_id = 'term-topic-photos' and (storage.foldername(name))[1] = auth.uid()::text);

-- ================================================================
-- VERIFY BEFORE TRUSTING THIS IS LIVE.
--
-- 1. Confirm the table + policies exist:
--    select policyname, cmd from pg_policies where tablename = 'student_term_topics';
--    select id, public from storage.buckets where id = 'term-topic-photos';
--
-- 2. As a student: upload a photo via /student/term-topics.html,
--    confirm it appears in their own gallery and the public URL
--    resolves in a plain browser tab (no auth header).
--
-- 3. As an assigned teacher: confirm the photo shows in
--    teacher/teacher.html's Student Info card for that student.
--
-- 4. As a teacher NOT assigned to that student: confirm the
--    student_term_topics query returns nothing for them.
-- ================================================================
