// Compiles curriculum source files to the SQL that loads them:
//   node curriculum/build-sql.js physics/energy
// writes supabase/curriculum_physics_energy.sql. Generated; edit the source
// (curriculum/physics/energy.js, curriculum/programmes.js), never the SQL. A
// test checks the SQL is current.
//
// The SQL is safe to re-run: rows are upserted by their permanent ids, and a
// concept's prerequisites, domains, specification links and misconception
// links are replaced as a set, so an edge removed from the source is removed
// from the database too. Requires mastery_engine_01 to have run first.

const fs = require('fs');
const path = require('path');
const { PROGRAMMES } = require('./programmes.js');

const q = v => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const arr = xs => (xs.length ? `array[${xs.map(q).join(', ')}]::text[]` : `'{}'::text[]`);
const json = v => `${q(JSON.stringify(v))}::jsonb`;

function subjectOf(conceptId) {
  const prefix = conceptId.split('.')[0];
  return { phy: 'Physics', che: 'Chemistry', bio: 'Biology', mat: 'Mathematics' }[prefix] || prefix;
}

function sql(name, { CONCEPTS, MISCONCEPTIONS }) {
  const ids = CONCEPTS.map(c => c.id);
  const status = Object.fromEntries(CONCEPTS.map(c => [c.id, c.status]));
  const out = [];
  out.push(`-- Curriculum data: ${name}. GENERATED by curriculum/build-sql.js from`);
  out.push(`-- curriculum/${name}.js and curriculum/programmes.js. Do not edit; edit the`);
  out.push('-- source and regenerate. Requires mastery_engine_01 to have run first.');
  out.push('-- Safe to re-run.');
  out.push('--');
  out.push('-- Run in the LIVE project only:');
  out.push('-- https://supabase.com/dashboard/project/ygtsrdwoikqnrbexjrtl/sql/new');
  out.push('');
  out.push('begin;');
  out.push('');
  out.push('-- Concepts');
  for (const c of CONCEPTS) {
    out.push(`insert into public.concepts (id, subject, home_domain, name, objective, tier, separate_only, required_contexts, evidence, boundaries, status, source_file)`);
    out.push(`values (${q(c.id)}, ${q(subjectOf(c.id))}, ${q(c.homeDomain)}, ${q(c.name)}, ${q(c.objective)}, ${q(c.tier)}, ${c.separateOnly}, ${arr(c.requiredContexts)}, ${json(c.evidence)}, ${arr(c.boundaries)}, ${q(c.status)}, ${q(`curriculum/${name}.js`)})`);
    out.push(`on conflict (id) do update set subject = excluded.subject, home_domain = excluded.home_domain, name = excluded.name, objective = excluded.objective, tier = excluded.tier, separate_only = excluded.separate_only, required_contexts = excluded.required_contexts, evidence = excluded.evidence, boundaries = excluded.boundaries, status = excluded.status, source_file = excluded.source_file, updated_at = now();`);
  }
  out.push('');
  out.push('-- Misconceptions (approved with the concepts they belong to)');
  for (const m of MISCONCEPTIONS) {
    const mStatus = m.status || (m.concepts.every(id => status[id] === 'approved') ? 'approved' : 'draft');
    out.push(`insert into public.misconceptions (id, subject, kind, statement, correct_conception, indicators, family, status)`);
    out.push(`values (${q(m.id)}, ${q(subjectOf(m.concepts[0]))}, ${q(m.kind)}, ${q(m.statement)}, ${q(m.correct)}, ${arr(m.indicators)}, ${q(m.family || null)}, ${q(mStatus)})`);
    out.push(`on conflict (id) do update set subject = excluded.subject, kind = excluded.kind, statement = excluded.statement, correct_conception = excluded.correct_conception, indicators = excluded.indicators, family = excluded.family, status = excluded.status, updated_at = now();`);
  }
  out.push('');
  out.push('-- Links are replaced as a set for these concepts');
  out.push(`delete from public.domain_concepts where concept_id in (${ids.map(q).join(', ')});`);
  out.push(`delete from public.concept_prerequisites where concept_id in (${ids.map(q).join(', ')});`);
  out.push(`delete from public.spec_statement_concepts where concept_id in (${ids.map(q).join(', ')});`);
  out.push(`delete from public.misconception_concepts where concept_id in (${ids.map(q).join(', ')});`);
  out.push('');
  for (const c of CONCEPTS) {
    out.push(`-- ${c.id}`);
    for (const d of c.domains) out.push(`insert into public.domain_concepts (domain, concept_id) values (${q(d)}, ${q(c.id)});`);
    for (const p of c.prerequisites) out.push(`insert into public.concept_prerequisites (concept_id, prerequisite_id, strength) values (${q(c.id)}, ${q(p.id)}, ${q(p.strength)});`);
    for (const s of c.spec) {
      out.push(`insert into public.spec_statements (curriculum, board, ref) values ('gcse-uk', ${q(s.board)}, ${q(s.ref)}) on conflict (curriculum, board, ref) do nothing;`);
      out.push(`insert into public.spec_statement_concepts (statement_id, concept_id, note) select id, ${q(c.id)}, ${q(s.note || null)} from public.spec_statements where curriculum = 'gcse-uk' and board = ${q(s.board)} and ref = ${q(s.ref)};`);
    }
    for (const mid of c.misconceptions) out.push(`insert into public.misconception_concepts (misconception_id, concept_id) values (${q(mid)}, ${q(c.id)});`);
  }
  out.push('');
  out.push('-- Programme sequences that use these concepts');
  for (const p of PROGRAMMES) {
    const units = p.units.filter(u => u.concepts.length === 0 || u.concepts.some(id => ids.includes(id)));
    if (!units.length) continue;
    p.units.forEach((u, i) => {
      out.push(`insert into public.programme_units (id, programme, subject, position, name) values (${q(u.id)}, ${q(p.id)}, ${q(p.subject)}, ${i + 1}, ${q(u.name)})`);
      out.push(`on conflict (id) do update set programme = excluded.programme, subject = excluded.subject, position = excluded.position, name = excluded.name;`);
    });
    for (const u of p.units) {
      const mine = u.concepts.filter(id => ids.includes(id));
      if (!mine.length) continue;
      out.push(`delete from public.programme_unit_concepts where unit_id = ${q(u.id)} and concept_id in (${mine.map(q).join(', ')});`);
      for (const id of mine) out.push(`insert into public.programme_unit_concepts (unit_id, concept_id) values (${q(u.id)}, ${q(id)});`);
    }
  }
  out.push('');
  out.push('commit;');
  out.push('');
  out.push(`-- Check. Expected: ${CONCEPTS.length} concepts (${CONCEPTS.filter(c => c.status === 'approved').length} approved), ${MISCONCEPTIONS.length} misconceptions, ${CONCEPTS.reduce((n, c) => n + c.prerequisites.length, 0)} prerequisite edges.`);
  out.push(`select (select count(*) from public.concepts where id in (${ids.map(q).join(', ')})) as concepts,`);
  out.push(`       (select count(*) from public.concepts where id in (${ids.map(q).join(', ')}) and status = 'approved') as approved,`);
  out.push(`       (select count(*) from public.misconceptions where id in (${MISCONCEPTIONS.map(m => q(m.id)).join(', ')})) as misconceptions,`);
  out.push(`       (select count(*) from public.concept_prerequisites where concept_id in (${ids.map(q).join(', ')})) as prerequisite_edges;`);
  out.push('');
  return out.join('\n');
}

if (require.main === module) {
  const name = process.argv[2];
  if (!name) { console.error('usage: node curriculum/build-sql.js physics/energy'); process.exit(1); }
  const dest = path.join(__dirname, '..', 'supabase', `curriculum_${name.replace('/', '_')}.sql`);
  fs.writeFileSync(dest, sql(name, require(path.join(__dirname, `${name}.js`))));
  console.log(`wrote ${path.relative(path.join(__dirname, '..'), dest)}`);
}

module.exports = { sql };
