// Renders a curriculum source file as readable concept cards for approval:
//   node curriculum/render-cards.js physics/energy
// writes docs/curriculum/physics-energy-concept-cards.md. The markdown is
// generated; edit the source file, never the output (a test checks it is
// current).

const fs = require('fs');
const path = require('path');

function render(name, { CONCEPTS, MISCONCEPTIONS }) {
  const mis = Object.fromEntries(MISCONCEPTIONS.map(m => [m.id, m]));
  const byId = Object.fromEntries(CONCEPTS.map(c => [c.id, c]));
  const out = [];
  out.push(`# Concept cards: ${name}`);
  out.push('');
  out.push(`*Generated from \`curriculum/${name}.js\` by \`curriculum/render-cards.js\`. Do not edit this file; edit the source.*`);
  out.push('');
  out.push(`${CONCEPTS.length} concepts · ${MISCONCEPTIONS.length} misconceptions · status: ${[...new Set(CONCEPTS.map(c => c.status))].join(', ')}`);
  out.push('');
  out.push('## Prerequisite map');
  out.push('');
  out.push('| Concept | Needs first (hard) | Helpful first (soft) |');
  out.push('|---|---|---|');
  for (const c of CONCEPTS) {
    const hard = c.prerequisites.filter(p => p.strength === 'hard').map(p => byId[p.id].name).join('; ') || '—';
    const soft = c.prerequisites.filter(p => p.strength === 'soft').map(p => byId[p.id].name).join('; ') || '—';
    out.push(`| ${c.name} | ${hard} | ${soft} |`);
  }
  out.push('');
  out.push('## Cards');
  for (const c of CONCEPTS) {
    out.push('');
    out.push(`### ${c.name}`);
    out.push('');
    out.push(`\`${c.id}\` · tier ${c.tier}${c.separateOnly ? ' · separate Physics only' : ''} · ${c.status}`);
    out.push('');
    out.push(`**A student who has mastered this can:** ${c.objective}`);
    out.push('');
    out.push(`- **Specification:** ${c.spec.map(s => `${s.board} ${s.ref}${s.note ? ` (${s.note})` : ''}`).join('; ')}`);
    if (c.domains.length > 1) out.push(`- **Also part of:** ${c.domains.filter(d => d !== c.homeDomain).join(', ')}`);
    out.push(`- **Evidence must cover:** ${c.requiredContexts.join(', ')}`);
    out.push(`- **Evidence rules:** ${c.evidence.numeric ? 'a numeric answer is required for Secure' : 'no numeric requirement'}; ${c.evidence.application ? 'an exam-style application item is required for Mastered' : 'no application item required'}; ${c.evidence.templated ? 'calculation templates suitable' : 'fixed items only'}`);
    if (c.boundaries.length) out.push(`- **Out of scope / boundaries:** ${c.boundaries.join('; ')}`);
    out.push(`- **Misconceptions:**`);
    for (const id of c.misconceptions) out.push(`  - \`${id}\` ${mis[id].statement} *Correct:* ${mis[id].correct}`);
  }
  out.push('');
  return out.join('\n');
}

if (require.main === module) {
  const name = process.argv[2];
  if (!name) { console.error('usage: node curriculum/render-cards.js physics/energy'); process.exit(1); }
  const src = require(path.join(__dirname, `${name}.js`));
  const dest = path.join(__dirname, '..', 'docs', 'curriculum', `${name.replace('/', '-')}-concept-cards.md`);
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, render(name, src));
  console.log(`wrote ${path.relative(path.join(__dirname, '..'), dest)}`);
}

module.exports = { render };
