// Generates the teacher guides for a school programme from the canonical
// sources, so they cannot drift from what the platform actually does:
//   curriculum/physics/energy.js            concepts, objectives, prerequisites, misconceptions
//   curriculum/school/physics-energy-v1.js  blocks, sessions, hinge questions, routine, policy
//   assets/js/mastery-rules.js              level rules, thresholds, remediation steps
//
//   node curriculum/school/build-guides.js          writes docs/school/physics-v1/guides/*.md
//   node curriculum/school/build-guides.js --check  exits 1 if any guide is out of date
//
// The lesson-specific delivery (minute-by-minute script, every answer and
// mark scheme) is in each block's teacher reference doc
// (curriculum/school/lessons/physics/<block>.teacher.html), which ISM Class
// shows beside the lesson. These guides are the programme knowledge a
// teacher needs around the lessons.

const fs = require('fs');
const path = require('path');
const { PROGRAMME } = require('./physics-energy-v1.js');
const { CONCEPTS, MISCONCEPTIONS } = require('../physics/energy.js');
const M = require('../../assets/js/mastery-rules.js');

const OUT = path.join(__dirname, '..', '..', 'docs', 'school', 'physics-v1', 'guides');
const C = Object.fromEntries(CONCEPTS.map(c => [c.id, c]));
const MIS = Object.fromEntries(MISCONCEPTIONS.map(m => [m.id, m]));
const R = M.RULES;
const LESSON_FILES = { B1: 'b1-toolkit', B2: 'b2-energy-stores-work' };

const ACTION_WORDS = {
  misconception_clinic: 'Misconception clinic', prerequisite_repair: 'Repair a prerequisite skill',
  worked_example_reteach: 'Re-teach with a worked example', second_mastery_check: 'Re-teach, then a second mastery check', escalate: 'See the pupil 1:1'
};

function header(title) {
  return [`# ${title}`, '', `*${PROGRAMME.product} · ${PROGRAMME.title} · ${PROGRAMME.version}. Generated by \`node curriculum/school/build-guides.js\` from the curriculum, the programme manifest and the mastery rules (${M.RULE_VERSION}). Do not edit by hand.*`, ''];
}

function remediationFor(misId) {
  const m = MIS[misId];
  if (!m) return '';
  const skill = m.concepts.find(c => /^phy\.skills\./.test(c));
  if (skill) return `Prerequisite repair: ${C[skill].name}. ${M.REMEDIATION_STEPS.prerequisite_repair.join(' → ')}.`;
  if (m.kind === 'conceptual') return `Misconception clinic. ${M.REMEDIATION_STEPS.misconception_clinic.join(' → ')}.`;
  return `Worked-example re-teach. ${M.REMEDIATION_STEPS.worked_example_reteach.join(' → ')}.`;
}

function secureRule() {
  return [
    `A concept is **Secure** when all of these hold (${M.RULE_VERSION}):`,
    '',
    `- at least ${R.secureCorrectInWindow} of the pupil's last ${R.secureWindow} answers on it are right, across at least ${R.secureMinDistinct} different questions;`,
    `- right answers in at least ${R.secureMinSessions} sessions at least ${R.secureSessionGapHours} hours apart;`,
    '- at least one right typed (numeric) or written answer, where the concept is a calculation;',
    `- at least one right answer at difficulty band ${R.secureMinBand} or above;`,
    '- at least one right **mastery-check** question (the diagnostic alone can never make a concept secure);',
    '- no likely misconception still open, and every required context covered.',
    '',
    `Guards: an MCQ answered right but "unsure" counts half; the same question again within ${R.reserveDays} days does not count again. **Mastered** also needs a right retrieval answer at least ${R.masteredRetrievalDays} days after becoming secure, and a right exam-style application question where the concept needs one. In a 6-week programme, expect Secure, not Mastered.`,
    ''
  ];
}

function programmeGuide() {
  const P = PROGRAMME;
  const L = header('Programme Delivery Guide');
  L.push('This guide is for any competent GCSE Physics teacher or tutor delivering the programme. It assumes no contact with the programme\'s author. Each block also has a block guide (below) and a lesson with its own teacher reference doc.', '');
  L.push('## What the programme is', '', P.spec.claim, '');
  L.push(`- **Specification:** ${P.spec.principal.board} ${P.spec.principal.codes.join(', ')}: ${P.spec.principal.sections.join('; ')}.`);
  L.push(`- **Excluded:** ${P.spec.excluded.join('; ')}.`);
  L.push(`- **Pupils:** groups of up to ${P.delivery.groupSize.ideal} (maximum ${P.delivery.groupSize.max}). Tier: ${P.delivery.tiers}.`);
  L.push(`- **Time:** ${P.delivery.weeks} weeks, ${P.delivery.sessionsPerWeek} sessions of ${P.delivery.sessionMinutes} minutes a week, plus ${P.delivery.independentMinutesPerWeek.join('–')} minutes of independent practice a week, a ${P.checks.baseline.minutes}-minute baseline check and a ${P.checks.reassessment.minutes}-minute reassessment.`, '');
  L.push('## Week by week', '', '| Week | Block | Content | Sessions |', '|---|---|---|---|');
  L.push(`| before 1 | Baseline | ${P.checks.baseline.purpose} | ${P.checks.baseline.minutes} min, on the platform |`);
  for (const b of P.blocks) L.push(`| ${b.week} | ${b.id} | ${b.title}${b.concepts.length ? ': ' + b.concepts.map(id => C[id].name).join('; ') : ''} | ${b.sessions.join(' + ')} |`);
  L.push('');
  L.push('## Before the first session', '',
    '1. Create the group on the Attendance page (groups are shared with attendance): add each pupil.',
    '2. Open **Teacher → Intervention**, choose the group, and start the programme with the date of the first session. Blocks then count as taught from the start of their week, so the platform shows "not yet taught", never "needs work", for later blocks.',
    '3. Copy the **Baseline check** link from the Intervention page to the pupils. They sign in, open it and answer on their own with no notes. It takes about 35 minutes and gives no grade.',
    '4. Read the mastery profile before planning Block 1. The baseline is an initial hypothesis: check anything surprising with the pupil.', '');
  L.push('## The loop in every block', '',
    '1. **Session 1 (teach):** the block lesson, Session 1, in ISM Class. Use the hinge questions to decide whether to move on.',
    '2. **Between sessions:** pupils do the block practice (link on the Intervention page) and the homework in the lesson.',
    '3. **Session 2 (consolidate):** clinic on the misconception most seen in exit tickets, harder practice, then the **block mastery check** on the platform (15 minutes, independent, no notes).',
    '4. **After the check:** open the Intervention page. For each pupil and concept you see the level, the evidence, the likely cause and the recommended next step. **Accept it, override it (choose another action and give a reason), or add a note.** The platform suggests; you decide, and your decision is kept beside its advice.',
    '5. **Remediate before moving on** (policy below). A second mastery check always uses questions the pupil has not seen.', '');
  L.push('## Session shapes', '');
  for (const [name, parts] of Object.entries(P.sessionShapes)) {
    L.push(`**${name}** (${parts.reduce((s, p) => s + p.min, 0)} min)`, '', '| Min | Part | What happens |', '|---|---|---|', ...parts.map(p => `| ${p.min} | ${p.part} | ${p.what} |`), '');
  }
  L.push('## The calculation routine (one routine, every calculation)', '', `Status: **${P.calculationRoutine.status}**.`, '', ...P.calculationRoutine.steps.map((s, i) => `${i + 1}. **${s.name}**: ${s.say}`), '');
  L.push('## Reading the mastery profile', '', '| Level | Meaning |', '|---|---|',
    '| Not yet taught | The block has not started. Planning only; never escalated. |',
    '| Not assessed | No answers yet. |',
    '| Too little evidence | Some answers, not enough to judge. A pupil whose first answers are right goes straight to a mastery check rather than being re-taught. |',
    `| Needs work | Recent accuracy below ${R.insecureAccuracy * 100}%, or a likely misconception, or a confidently wrong answer. |`,
    `| Developing | At least ${R.developingMinItems} different questions and recent accuracy (weighted to the latest) of ${R.developingAccuracy * 100}% or more. |`,
    '| Secure | See below. |', '| Mastered | Secure, plus delayed retrieval and exam application. |', '');
  L.push(...secureRule());
  L.push('## Why a pupil is struggling: causes', '',
    'The platform separates pupils who reach the same score for different reasons:', '',
    '- **A prerequisite skill:** the wrong answers are skill errors (units, rearranging, standard form, graphs), or a hard prerequisite is itself insecure. Repair the skill first; re-teaching the physics will not help.',
    '- **A misconception:** the pupil chose answers that signal a known wrong idea (from the programme\'s misconception library). Unpick the idea with contrasting cases.',
    '- **A method error:** a procedure specific to this concept (e.g. forgetting to square the speed). Re-teach with a worked example, then a faded one.',
    '- **Slips:** wrong answers with no pattern. Practise, and check accuracy habits.', '',
    `A misconception is **possible** after one selection, **likely** after ${R.likelyMinItems} selections on different questions (at least one answered "sure"), and **resolved** after ${R.resolvedMinCorrect} later right answers on questions that offered it, in ${R.resolvedMinSessions} sessions. Nobody is labelled from one answer.`, '');
  L.push('## Remediation policy', '', `- **Pass:** ${P.remediationPolicy.passThreshold}`, `- **After a first fail:** ${P.remediationPolicy.afterFirstFail}`, `- **After a second fail:** ${P.remediationPolicy.afterSecondFail}`, `- **Never:** ${P.remediationPolicy.neverDo}`, '');
  L.push('Remediation steps by recommended action:', '');
  for (const [a, steps] of Object.entries(M.REMEDIATION_STEPS)) L.push(`- **${ACTION_WORDS[a] || a}:** ${steps.join(' → ')}.`);
  L.push('');
  L.push('## When to see a pupil 1:1 (escalation flags)', '',
    `- **E1, wheel-spin:** ${R.e1Opportunities} or more answers on a concept without becoming secure, or ${R.failedChecksBeforeEscalation} failed mastery checks.`,
    `- **E2, stuck prerequisite:** a hard prerequisite still insecure after ${R.failedChecksBeforeEscalation} checks.`,
    '- **E3, persistent misconception:** a likely misconception seen in 3 or more sessions.',
    '- Also: repeated absence, very fast answers (guessing), or anything worrying about wellbeing. **Safeguarding concerns go to the school\'s Designated Safeguarding Lead, never into learning notes.**', '');
  L.push('## Reassessment and the school report', '',
    `- In week 6, pupils take the **Reassessment** (${P.checks.reassessment.minutes} min). ${P.checks.reassessment.purpose}`,
    '- **Teacher → Intervention → School report** produces the report from recorded data: attendance, baseline, priorities, pathways, block checks, a like-for-like comparison, the current profile, individual summaries and next steps. Print or save it as a PDF.',
    '- Say "evidence indicates", "current mastery profile", "performance on these questions changed from … to …". Never say the programme *caused* a change, never convert results to grades, and never report percentages for a single concept.', '');
  L.push('## Evidence integrity', '',
    '- Checks are done alone, without notes, on the platform. If a pupil had help, add a note and do not count it.',
    '- Mastery-check questions are never shown in lessons, worksheets or reviews before the check. The question files are not public.',
    '- Past-paper questions may be referenced by paper and question number from the school\'s own copies; Inspire does not distribute them.', '');
  return L.join('\n');
}

function blockGuide(b) {
  const L = header(`Block guide: ${b.id} ${b.title} (week ${b.week})`);
  L.push(`**Intent.** ${b.intent}`, '');
  const lessonFile = LESSON_FILES[b.id];
  L.push('## Lesson', '', `- Status: **${b.lesson.status}**${b.lesson.qa ? ` (QA: \`${b.lesson.qa}\`)` : ''}.`);
  if (lessonFile) L.push(`- Pupil lesson: \`curriculum/school/lessons/physics/${lessonFile}.html\` (upload to ISM Class as the lesson).`, `- Teacher reference doc: \`curriculum/school/lessons/physics/${lessonFile}.teacher.html\` (upload in the teacher-doc slot): minute-by-minute plan, every answer and mark scheme.`);
  else L.push(`- Not yet written. Needed: ${b.lesson.need}`);
  L.push('');
  if (b.concepts.length) {
    L.push('## Platform links (Teacher → Intervention)', '', `- Practice between sessions: \`${PROGRAMME.id}:${b.id}-practice\``, `- Block mastery check (end of Session 2): \`${PROGRAMME.id}:${b.id}\``, '');
    L.push('## Concepts', '');
    for (const id of b.concepts) {
      const c = C[id];
      L.push(`### ${c.name}`, '', `\`${c.id}\` · ${c.spec.map(s => `${s.board} ${s.ref}`).join('; ')} · tier ${c.tier}`, '', `**Objective.** ${c.objective}`, '');
      L.push(`**Prerequisites.** ${c.prerequisites.length ? c.prerequisites.map(p => `${C[p.id].name} (${p.strength})`).join('; ') : 'none'}.`, '');
      L.push(`**Secure evidence must cover.** ${c.requiredContexts.join('; ')}${c.evidence.numeric ? '; includes a typed numeric answer' : ''}.`, '');
      if (c.boundaries.length) L.push(`**Out of scope here.** ${c.boundaries.join('; ')}.`, '');
      L.push('| Misconception | The correct idea | What it looks like | If you see it |', '|---|---|---|---|');
      for (const mid of c.misconceptions) {
        const m = MIS[mid];
        L.push(`| \`${m.id}\` ${m.statement} | ${m.correct} | ${(m.indicators || []).join('; ')} | ${remediationFor(m.id)} |`);
      }
      L.push('');
    }
    if (b.hingeQuestions.length) {
      L.push('## Hinge questions (ask, then decide whether to move on)', '');
      b.hingeQuestions.forEach((h, i) => L.push(`${i + 1}. **${h.q}**`, `   - Answer: ${h.a}`, `   - Wrong answers usually mean: ${h.watch.map(id => `\`${id}\` ${MIS[id].statement}`).join(' / ')}`, ''));
    }
    if (b.stretch) L.push('## Stretch', '', b.stretch, '');
    L.push(...secureRule());
  }
  if (b.teacherNotes.length) L.push('## Notes for the teacher', '', ...b.teacherNotes.map(n => `- ${n}`), '');
  return L.join('\n');
}

function build() {
  const files = { '00-programme.md': programmeGuide() + '\n' };
  for (const b of PROGRAMME.blocks) files[`${b.id}.md`] = blockGuide(b) + '\n';
  return files;
}

if (require.main === module) {
  const files = build();
  if (process.argv.includes('--check')) {
    const stale = Object.entries(files).filter(([f, text]) => {
      const p = path.join(OUT, f);
      return !fs.existsSync(p) || fs.readFileSync(p, 'utf8').replace(/\r\n/g, '\n') !== text;
    });
    if (stale.length) { console.error('Out of date:', stale.map(([f]) => f).join(', ')); process.exit(1); }
    console.log('guides current');
  } else {
    fs.mkdirSync(OUT, { recursive: true });
    for (const [f, text] of Object.entries(files)) fs.writeFileSync(path.join(OUT, f), text);
    console.log(`wrote ${Object.keys(files).length} guides to docs/school/physics-v1/guides/`);
  }
}

module.exports = { build };
